"""Seed data for the three demo tenants, ported from apps/server/src/db/seed/data.ts.

Apex Bank carries the designed scenario; times are minutes/days relative to the seed clock."""

from __future__ import annotations

from typing import Any

ACTION_TEMPLATES: list[Any] = [
    {
        "code": "ACT-STM-002",
        "name": "Generate and email account statement",
        "owner": "Retail Ops",
        "system": "Statement service",
        "endpoint": "STM_GEN",
        "rev": True,
        "money": False,
        "approval": "auto",
        "stp": 97,
        "vol": 612,
    },
    {
        "code": "ACT-LTR-011",
        "name": "Issue balance confirmation letter",
        "owner": "Retail Ops",
        "system": "Doc service",
        "endpoint": "LTR_BAL",
        "rev": True,
        "money": False,
        "approval": "auto",
        "stp": 95,
        "vol": 287,
    },
    {
        "code": "ACT-CRT-004",
        "name": "Re-send interest certificate",
        "owner": "Retail Ops",
        "system": "Doc service",
        "endpoint": "CRT_INT",
        "rev": True,
        "money": False,
        "approval": "auto",
        "stp": 96,
        "vol": 203,
    },
    {
        "code": "ACT-KYC-021",
        "name": "Update registered mobile (OTP verified)",
        "owner": "Retail Ops",
        "system": "Finacle API",
        "endpoint": "KYC_MOB_V1",
        "rev": True,
        "money": False,
        "approval": "single",
        "stp": 88,
        "vol": 166,
    },
    {
        "code": "ACT-CHQ-001",
        "name": "Request cheque book",
        "owner": "Retail Ops",
        "system": "Finacle API",
        "endpoint": "CHQ_BOOK",
        "rev": True,
        "money": False,
        "approval": "auto",
        "stp": 94,
        "vol": 141,
    },
    {
        "code": "ACT-SI-009",
        "name": "Register standing instruction (non-financial hold)",
        "owner": "Payments",
        "system": "Finacle API",
        "endpoint": "SI_REG",
        "rev": True,
        "money": False,
        "approval": "single",
        "stp": 79,
        "vol": 94,
    },
    {
        "code": "ACT-ACC-030",
        "name": "Close dormant savings account",
        "owner": "Retail Ops",
        "system": "Finacle API",
        "endpoint": "ACC_CLOSE",
        "rev": False,
        "money": False,
        "approval": "dual",
        "stp": 61,
        "vol": 58,
    },
    {
        "code": "ACT-NOM-006",
        "name": "Withdraw nomination on account",
        "owner": "Retail Ops",
        "system": "Finacle API",
        "endpoint": "NOM_WD",
        "rev": False,
        "money": False,
        "approval": "dual",
        "stp": 55,
        "vol": 41,
    },
    {
        "code": "ACT-LKR-003",
        "name": "Surrender locker facility",
        "owner": "Branch Ops",
        "system": "Branch workflow",
        "endpoint": "LKR_SUR",
        "rev": False,
        "money": False,
        "approval": "dual",
        "stp": 48,
        "vol": 22,
    },
    {
        "code": "ACT-DIG-014",
        "name": "De-register net banking user",
        "owner": "Digital",
        "system": "Channel admin",
        "endpoint": "DIG_DEREG",
        "rev": False,
        "money": False,
        "approval": "dual",
        "stp": 66,
        "vol": 77,
    },
    {
        "code": "ACT-ACC-041",
        "name": "Convert account to former-or-survivor",
        "owner": "Retail Ops",
        "system": "Finacle API",
        "endpoint": "ACC_MODE",
        "rev": False,
        "money": False,
        "approval": "dual",
        "stp": 52,
        "vol": 35,
    },
    {
        "code": "ACT-DSP-003",
        "name": "Raise provisional credit on dispute",
        "owner": "Disputes",
        "system": "Finacle API",
        "endpoint": "DSP_PROV_CR",
        "rev": True,
        "money": True,
        "approval": "dual",
        "stp": 58,
        "vol": 188,
    },
    {
        "code": "ACT-FEE-002",
        "name": "Reverse service charge",
        "owner": "Retail Ops",
        "system": "Finacle API",
        "endpoint": "FEE_REV",
        "rev": True,
        "money": True,
        "approval": "single",
        "stp": 84,
        "vol": 412,
    },
    {
        "code": "ACT-FEE-017",
        "name": "Waive late payment fee",
        "owner": "Cards",
        "system": "Cards system",
        "endpoint": "CRD_FEE_WV",
        "rev": True,
        "money": True,
        "approval": "single",
        "stp": 81,
        "vol": 236,
    },
    {
        "code": "ACT-CRD-008",
        "name": "Place temporary hold on card",
        "owner": "Cards",
        "system": "Cards system",
        "endpoint": "CRD_HOLD",
        "rev": True,
        "money": True,
        "approval": "single",
        "stp": 90,
        "vol": 304,
    },
    {
        "code": "ACT-PAY-025",
        "name": "Reverse duplicate NEFT within cut-off",
        "owner": "Payments",
        "system": "Payments hub",
        "endpoint": "NEFT_REV",
        "rev": True,
        "money": True,
        "approval": "dual",
        "stp": 49,
        "vol": 64,
    },
    {
        "code": "ACT-STP-014",
        "name": "Place stop payment on cheque instrument",
        "owner": "Payments",
        "system": "Finacle API",
        "endpoint": "CHQ_STOP_V2",
        "rev": False,
        "money": True,
        "approval": "dual",
        "stp": None,
        "vol": 148,
    },
    {
        "code": "ACT-REM-001",
        "name": "Execute outward remittance",
        "owner": "Trade & Payments",
        "system": "SWIFT gateway",
        "endpoint": "MT103",
        "rev": False,
        "money": True,
        "approval": "dual",
        "stp": None,
        "vol": 96,
    },
    {
        "code": "ACT-LON-012",
        "name": "Foreclose loan account",
        "owner": "Lending",
        "system": "Loan system",
        "endpoint": "LN_CLOSE",
        "rev": False,
        "money": True,
        "approval": "dual",
        "stp": None,
        "vol": 73,
    },
    {
        "code": "ACT-TD-005",
        "name": "Break term deposit before maturity",
        "owner": "Retail Ops",
        "system": "Finacle API",
        "endpoint": "TD_BREAK",
        "rev": False,
        "money": True,
        "approval": "dual",
        "stp": None,
        "vol": 129,
    },
    {
        "code": "ACT-FWD-002",
        "name": "Book forward contract",
        "owner": "Trade Finance",
        "system": "Treasury system",
        "endpoint": "FWD_BOOK",
        "rev": False,
        "money": True,
        "approval": "dual",
        "stp": None,
        "vol": 54,
    },
    {
        "code": "ACT-LON-007",
        "name": "Send loan foreclosure quote",
        "owner": "Lending",
        "system": "Loan system",
        "endpoint": "LN_QUOTE",
        "rev": True,
        "money": False,
        "approval": "single",
        "stp": 92,
        "vol": 176,
    },
]

AGENTS: list[Any] = [
    {
        "name": "Retail Bucketer",
        "abbr": "RB",
        "template": "bucketing",
        "role": "bucketer",
        "model": "claude-sonnet-5",
        "boards": ["retail", "nri"],
        "cost": 19,
        "score": 94,
        "state": "live",
        "version": 7,
        "prompt": "You sort incoming retail banking email into exactly one query type from the approved taxonomy. Return the type, a confidence between 0 and 1, and the three phrases that drove the "
        'choice. If two types fit equally, return neither — return "ambiguous" and let a person decide.',
        "evals": [
            ["Routing accuracy", "94.2%", "ok"],
            ["Wrong type sent through", "1.8%", "ok"],
            ["Ambiguous, handed over", "4.0%", "neutral"],
            ["Drift vs last version", "+0.6pt", "ok"],
        ],
    },
    {
        "name": "Trade Bucketer",
        "abbr": "TB",
        "template": "bucketing",
        "role": "bucketer",
        "model": "claude-sonnet-5",
        "boards": ["trade"],
        "cost": 24,
        "score": 87,
        "state": "live",
        "version": 4,
        "prompt": "You sort trade finance and payments email into one query type. Trade instructions carry money and deadlines, so bias toward handing over when the instrument, the amount or the value "
        "date is not stated explicitly.",
        "evals": [
            ["Routing accuracy", "87.1%", "warn"],
            ["Wrong type sent through", "2.4%", "ok"],
            ["Ambiguous, handed over", "10.5%", "neutral"],
            ["Drift vs last version", "−0.9pt", "warn"],
        ],
    },
    {
        "name": "Field Extractor",
        "abbr": "FE",
        "template": "extraction",
        "role": "extractor",
        "model": "claude-sonnet-5",
        "boards": ["retail", "trade"],
        "cost": 31,
        "score": 96,
        "state": "live",
        "version": 11,
        "prompt": "You pull the fields an action template needs out of an email thread. Every value must be quoted verbatim from the thread or a system record — mark anything you inferred, and never guess "
        "an amount, an account number or a date.",
        "evals": [
            ["Field accuracy", "96.4%", "ok"],
            ["Hallucinated value", "0.0%", "ok"],
            ["Missing field, handed over", "3.6%", "neutral"],
            ["Drift vs last version", "+0.2pt", "ok"],
        ],
    },
    {
        "name": "Reply Drafter",
        "abbr": "RD",
        "template": "drafting",
        "role": "drafter",
        "model": "claude-sonnet-5",
        "boards": ["retail", "nri", "trade"],
        "cost": 42,
        "score": 91,
        "state": "live",
        "version": 9,
        "prompt": "You draft a reply using only knowledge-manager-approved sources, citing each one. Where the approved material does not cover part of the question, say so plainly in the draft and raise "
        "a gap ticket. Never fill a gap from memory.",
        "evals": [
            ["Sent as drafted", "78%", "ok"],
            ["Grounded in a source", "100%", "ok"],
            ["Tone rejected by staff", "4.1%", "neutral"],
            ["Drift vs last version", "+1.1pt", "ok"],
        ],
    },
    {
        "name": "Dispute Summariser",
        "abbr": "DS",
        "template": "summarisation",
        "role": "summariser",
        "model": "claude-sonnet-5",
        "boards": ["disputes"],
        "cost": 28,
        "score": 89,
        "state": "live",
        "version": 3,
        "prompt": "You brief a human on a disputed transaction. Assemble the dispute history, the merchant record, the chargeback clock and the provisional credit position. You never write to the customer "
        "on this board.",
        "evals": [
            ["Brief rated useful", "89%", "ok"],
            ["Missed a prior contact", "2.2%", "ok"],
            ["Clock stated wrongly", "0.4%", "ok"],
            ["Drift vs last version", "new", "neutral"],
        ],
    },
    {
        "name": "Priority Ranker",
        "abbr": "PR",
        "template": "policy_guard",
        "role": "ranker",
        "model": "rules + claude-haiku-4-5",
        "boards": ["retail", "nri", "trade", "disputes"],
        "cost": 2,
        "score": 97,
        "state": "live",
        "version": 14,
        "prompt": "You set and continuously update ticket priority from rules over ticket attributes: deadline distance, amount at stake, repeat contacts, sentiment, regulatory keywords and customer "
        "segment. Rules fire deterministically; the model only breaks ties. You re-rank the queue every five minutes and on every new event.",
        "evals": [
            ["Priority accepted by staff", "97.1%", "ok"],
            ["Manual overrides", "2.9%", "neutral"],
            ["Missed escalation", "0.1%", "ok"],
            ["Drift vs last version", "+0.4pt", "ok"],
        ],
    },
    {
        "name": "Guardrail Sentinel",
        "abbr": "GS",
        "template": "policy_guard",
        "role": "guard",
        "model": "claude-haiku-4-5",
        "boards": ["retail", "nri", "trade", "disputes", "grievance"],
        "cost": 4,
        "score": 99,
        "state": "live",
        "version": 22,
        "prompt": "You read every thread before anything else runs and stop the pipeline on a hard rule: a named regulator, a legal notice, suspected fraud, a vulnerable-customer signal, or a third repeat "
        "contact. You never generate customer-facing text.",
        "evals": [
            ["Hard stops caught", "99.6%", "ok"],
            ["False stop", "1.2%", "neutral"],
            ["Missed escalation", "0.0%", "ok"],
            ["Drift vs last version", "+0.1pt", "ok"],
        ],
    },
]

ALERTS: list[Any] = [
    {
        "sevLabel": "LATE IN 26m",
        "sevKind": "late",
        "bucket": "Disputed transactions",
        "text": "QRY-48199 has been open 15 days with an ombudsman threat on the thread. The provisional credit window lapsed on 17 Jul.",
        "action": "Escalate to Disputes lead",
        "owner": "R. Menon",
        "minAgo": 0,
    },
    {
        "sevLabel": "PATTERN",
        "sevKind": "pattern",
        "bucket": "Account maintenance",
        "text": "Nine near-identical NRE joint-holder queries in 90 minutes. Likely a broken help-centre link rather than a genuine spike.",
        "action": "Open content investigation",
        "owner": "Knowledge",
        "minAgo": 32,
    },
    {
        "sevLabel": "CONFIDENCE DRIFT",
        "sevKind": "drift",
        "bucket": "Trade finance advisory",
        "text": "Average confidence here fell from 0.81 to 0.72 over four days. Correlates with the un-refreshed Forward Cover Policy.",
        "action": "Request source refresh",
        "owner": "Trade Fin.",
        "minAgo": 60,
    },
    {
        "sevLabel": "CAPACITY",
        "sevKind": "capacity",
        "bucket": "Chargeback & Disputes",
        "text": "Two of five disputes handlers are on leave tomorrow. Projected 11 threads past deadline unless the rotation is widened.",
        "action": "Widen rotation pool",
        "owner": "Workforce",
        "minAgo": 120,
    },
]

BACKGROUND_LOAD: dict[str, Any] = {
    "P. Sharma": 3,
    "R. Menon": 2,
    "A. Kapoor": 0,
    "A. Fernandes": 4,
    "S. Qureshi": 13,
    "D. Kulkarni": 4,
    "L. Thomas": 9,
}

BOARDS: list[Any] = [
    {
        "key": "retail",
        "name": "Retail mail",
        "mailbox": "customercare@bank.example",
        "team": "Retail pod 1 · 8 people",
        "state": "live",
        "auto": 74,
        "agents": [
            "Retail Bucketer",
            "Field Extractor",
            "Reply Drafter",
            "Guardrail Sentinel",
            "Priority Ranker",
        ],
    },
    {
        "key": "nri",
        "name": "NRI desk",
        "mailbox": "nri.desk@bank.example",
        "team": "Retail pod 2 · 4 people",
        "state": "live",
        "auto": 68,
        "agents": ["Retail Bucketer", "Reply Drafter", "Guardrail Sentinel", "Priority Ranker"],
    },
    {
        "key": "trade",
        "name": "Trade operations",
        "mailbox": "tradeops@bank.example",
        "team": "Trade & Payments · 6 people",
        "state": "live",
        "auto": 52,
        "agents": [
            "Trade Bucketer",
            "Field Extractor",
            "Guardrail Sentinel",
            "Priority Ranker",
            "Reply Drafter",
        ],
    },
    {
        "key": "disputes",
        "name": "Disputes",
        "mailbox": "disputes@bank.example",
        "team": "Disputes · 5 people",
        "state": "triage_only",
        "auto": 21,
        "agents": ["Dispute Summariser", "Guardrail Sentinel", "Priority Ranker"],
    },
    {
        "key": "grievance",
        "name": "Grievance",
        "mailbox": "grievance@bank.example",
        "team": "Compliance · 3 people",
        "state": "observe",
        "auto": 0,
        "agents": ["Guardrail Sentinel"],
    },
]

BUCKET_RULES: list[Any] = [
    {
        "description": "Subject or body contains “stop payment” plus a cheque-number pattern",
        "target": "Stop payment instruction",
        "kind": "Deterministic",
        "hits": "148 / mo",
        "pattern": {
            "all": ["stop"],
            "regex": "cheque\\s*(?:no\\.?|number)?\\s*\\d{6}",
            "queryType": "Stop payment instruction",
        },
    },
    {
        "description": "Attachment matches the dispute form template",
        "target": "Disputed transactions",
        "kind": "Deterministic",
        "hits": "96 / mo",
        "pattern": {"any": ["dispute form"], "queryType": "Disputed transactions"},
    },
    {
        "description": "Sender domain belongs to a corporate CIF",
        "target": "Routed to Trade & Payments first",
        "kind": "Deterministic",
        "hits": "412 / mo",
        "pattern": None,
    },
    {
        "description": "Two or more intents detected in one email",
        "target": "Multi-intent — split proposed, human decides",
        "kind": "Model + rule",
        "hits": "61 / mo",
        "pattern": None,
    },
    {
        "description": "No rule fires",
        "target": "Model classification, 0.78 confidence bar",
        "kind": "Model",
        "hits": "2,197 / mo",
        "pattern": None,
    },
]

CELL_COUNTS: dict[str, Any] = {"0-0": 34, "0-1": 19, "1-0": 12, "1-1": 8}

CONNECTORS: list[Any] = [
    {
        "abbr": "CBS",
        "name": "Finacle core banking",
        "scope": "6 read endpoints · 4 write, per action",
        "state": "connected",
    },
    {
        "abbr": "CRM",
        "name": "Customer 360",
        "scope": "read only · mandate & CIF lookup",
        "state": "connected",
    },
    {
        "abbr": "CRD",
        "name": "Cards management system",
        "scope": "2 write endpoints · hold, fee reversal",
        "state": "connected",
    },
    {"abbr": "PAY", "name": "Payments hub", "scope": "read · write gated to phase 4", "state": "read_only"},
    {"abbr": "SWF", "name": "SWIFT gateway", "scope": "no automated write, ever", "state": "suggest_only"},
]

COURSES: list[Any] = [
    {
        "key": "disputes",
        "title": "Disputes: the 5-day window",
        "minutes": 3,
        "baseline": 64,
        "cards": [
            {
                "title": "What changed",
                "body": "The provisional credit window for disputed card transactions dropped from 7 days to 5 working days, effective 24 July.",
            },
            {
                "title": "What you say",
                "body": "Commit to provisional credit within 5 working days of a valid dispute — never promise “about a week” anymore.",
            },
            {
                "title": "What the AI does",
                "body": "The Dispute Summariser now flags any dispute at day 3 as amber and day 4 as red, and the deadline clock reflects 5 days.",
            },
        ],
        "quiz": [
            {
                "q": "A valid card dispute was raised 4 working days ago with no credit posted. What is it?",
                "options": [
                    "On track — the window is 7 days",
                    "One day from breach — escalate today",
                    "Already in breach",
                ],
                "correct": 1,
            },
            {
                "q": "What may you promise a customer on the phone?",
                "options": [
                    "Credit “within about a week”",
                    "Credit within 5 working days",
                    "No commitment at all",
                ],
                "correct": 1,
            },
        ],
    },
    {
        "key": "vulnerable",
        "title": "Vulnerable customer signals",
        "minutes": 2,
        "baseline": 41,
        "cards": [
            {
                "title": "The new rule",
                "body": "Bereavement, serious illness and financial-distress language now fire a hard stop: the AI writes nothing customer-facing on the thread.",
            },
            {
                "title": "Why",
                "body": "These conversations need judgement and warmth, not a template. The AI still assembles context so you start briefed.",
            },
            {
                "title": "Your move",
                "body": "Take the thread over, acknowledge the situation in your own words first, then handle the banking need.",
            },
        ],
        "quiz": [
            {
                "q": "An email mentions the account holder passed away. The AI should…",
                "options": [
                    "Draft a condolence reply for you to send",
                    "Stop drafting and hand you the context",
                    "Route it to legal automatically",
                ],
                "correct": 1,
            }
        ],
    },
    {
        "key": "nre",
        "title": "NRE accounts refresher",
        "minutes": 4,
        "baseline": 88,
        "cards": [
            {
                "title": "Joint holders",
                "body": "A resident may be added to an NRE account only on a former-or-survivor basis, with the non-resident as the former.",
            },
            {
                "title": "Status",
                "body": "Adding a resident joint holder does not change the account’s NRE status or its tax treatment.",
            },
        ],
        "quiz": [
            {
                "q": "A resident daughter is added to her father’s NRE account. The operating mode must be…",
                "options": [
                    "Either or survivor",
                    "Former or survivor, non-resident as former",
                    "Jointly operated",
                ],
                "correct": 1,
            }
        ],
    },
]

DEPARTMENTS: list[Any] = [
    {
        "name": "Retail Service Desk",
        "owner": "A. Fernandes",
        "readiness": 86,
        "note": "142 approved articles · 4 stale",
        "gapNote": "Locker rent waiver has no owner — cannot be automated until one is named.",
        "risk": False,
        "inMatrix": True,
    },
    {
        "name": "Trade & Payments",
        "owner": "D. Kulkarni",
        "readiness": 52,
        "note": "31 approved · policy notes un-owned",
        "gapNote": "Forward cover advisory blocked on GAP-0412.",
        "risk": False,
        "inMatrix": True,
    },
    {
        "name": "Chargeback & Disputes",
        "owner": "S. Qureshi",
        "readiness": 38,
        "note": "largely tribal — biggest single blocker",
        "gapNote": "Lowest knowledge readiness in the bank. Two blocking gaps, one conflict.",
        "risk": True,
        "inMatrix": True,
    },
    {
        "name": "Retail Lending",
        "owner": "L. Thomas",
        "readiness": 61,
        "note": "44 approved · foreclosure math is live",
        "gapNote": "",
        "risk": False,
        "inMatrix": True,
    },
    {
        "name": "Cards",
        "owner": "S. Qureshi",
        "readiness": 74,
        "note": "68 approved · fee schedule refresh due",
        "gapNote": "",
        "risk": False,
        "inMatrix": True,
    },
]

DIAL: dict[str, Any] = {"0-0": 2, "0-1": 1, "1-0": 1, "1-1": 0}

EXTRA_GAPS: list[Any] = [
    ["Fee reversal eligibility for premium current accounts", "Retail Ops"],
    ["Cheque return charges for technical reasons", "Retail Ops"],
    ["Minor account conversion on turning 18", "Retail Ops"],
    ["LC amendment fee after expiry", "Trade Finance"],
    ["EMI moratorium for medical emergencies", "Lending"],
    ["Card replacement fee when damaged abroad", "Cards"],
    ["Chargeback evidence list for subscription merchants", "Disputes"],
    ["NRO repatriation limit documentation", "Retail Ops"],
]

FEEDBACK: list[Any] = [
    {
        "agent": "Retail Bucketer",
        "ticket": "QRY-48102",
        "kind": "override",
        "text": "Filed as account maintenance; staff moved it to disputes — the word “unauthorised” sat in a forwarded footer.",
        "fix": "context",
        "daysAgo": 2,
    },
    {
        "agent": "Reply Drafter",
        "ticket": "QRY-48079",
        "kind": "edit",
        "text": "Opened with an apology template on a neutral query; staff cut it. Third such edit this month.",
        "fix": "prompt",
        "daysAgo": 3,
    },
    {
        "agent": "Field Extractor",
        "ticket": "QRY-48031",
        "kind": "rejection",
        "text": "Reason code inferred as DISPUTE; correct was CONTRACT_TERMINATED. Correction stored.",
        "fix": "context",
        "daysAgo": 12,
    },
    {
        "agent": "Trade Bucketer",
        "ticket": "QRY-47990",
        "kind": "override",
        "text": "LC amendment misfiled as a remittance query. Second similar case this month.",
        "fix": "context",
        "daysAgo": 7,
    },
    {
        "agent": "Priority Ranker",
        "ticket": "QRY-47881",
        "kind": "override",
        "text": "Set P3 on a bereavement thread; staff raised it to P1. The vulnerable-customer rule was added off the back of this.",
        "fix": "prompt",
        "daysAgo": 14,
    },
]

GAPS: list[Any] = [
    {
        "number": 412,
        "severity": "blocking",
        "question": "Can export receivables substitute for a cash margin on a forward contract under DA 90 terms?",
        "detail": "Forward Cover Policy §2.1 covers tenor but is silent on receivables as margin. Trade desk answers this verbally today, which means it cannot be automated or audited.",
        "hits": 34,
        "openDays": 3,
        "owner": "Trade Finance",
        "state": "Draft with owner",
        "cta": "Review draft",
    },
    {
        "number": 409,
        "severity": "blocking",
        "question": "What is the provisional credit timeline for international card disputes above ₹50,000?",
        "detail": "Two conflicting internal notes exist — one from 2023, one from 2026. The agent refuses to choose between them and routes every such query to a human.",
        "hits": 88,
        "openDays": 6,
        "owner": "Disputes",
        "state": "Conflict, needs adjudication",
        "cta": "Adjudicate",
    },
    {
        "number": 407,
        "severity": "stale",
        "question": "Current schedule of charges for NRE / NRO account maintenance",
        "detail": "Source last verified 94 days ago and the fee revision circular of 1 July is not reflected. The agent is still citing it but has downgraded confidence by 0.12.",
        "hits": 51,
        "openDays": 9,
        "owner": "Retail Ops",
        "state": "Refresh requested",
        "cta": "Attach circular",
    },
    {
        "number": 402,
        "severity": "unowned",
        "question": "Who signs off on locker rent waiver requests above one year?",
        "detail": "No department has claimed this query type, so no one can approve content for it. 19 queries have been routed manually this month with inconsistent answers.",
        "hits": 19,
        "openDays": 21,
        "owner": "Unassigned",
        "state": "Needs an owner",
        "cta": "Assign owner",
    },
    {
        "number": 398,
        "severity": "resolved",
        "question": "Documentation for adding a resident joint holder to an NRE account",
        "detail": "FEMA Compliance Note 2026-03 published and approved 4 days ago. Confidence here recovered from 0.61 to 0.88 within a day.",
        "hits": 0,
        "openDays": 12,
        "owner": "Compliance",
        "state": "Live in drafts",
        "cta": "View source",
        "closedDaysAgo": 4,
    },
]

KDOCS: list[Any] = [
    {
        "key": "nre",
        "source": "Policy SharePoint",
        "title": "NRE Account Operations Manual",
        "section": "§4.2 Joint holder addition",
        "owner": "S. Iyer",
        "dept": "Retail Service Desk",
        "status": "approved",
        "verifiedDaysAgo": 11,
        "body": "A resident individual may be added as a joint holder to an NRE savings account. Required: a joint holder addition request signed by both parties; the resident holder's PAN, Aadhaar and a "
        "recent photograph; address proof for the resident holder; a copy of the non-resident holder's passport and valid visa page, attested by an Indian mission or a notary. Documents may be "
        "submitted through the nearest Indian mission or a notary abroad; travel to India is not required. The update is completed within two working days of receipt.",
    },
    {
        "key": "fema",
        "source": "Compliance circulars",
        "title": "FEMA Compliance Note 2026-03",
        "section": "Resident joint holders",
        "owner": "Compliance",
        "dept": "Retail Service Desk",
        "status": "approved",
        "verifiedDaysAgo": 4,
        "body": "Where a resident individual is added to an NRE account, the account must be operated on a former-or-survivor basis with the non-resident holder as the former. The account retains its NRE "
        "status and its tax treatment is unchanged.",
    },
    {
        "key": "fwd",
        "source": "Policy SharePoint",
        "title": "Forward Cover Policy",
        "section": "§2.1 Tenor limits, firm orders",
        "owner": "Trade Finance",
        "dept": "Trade & Payments",
        "status": "approved",
        "verifiedDaysAgo": 22,
        "body": "For a firm export order, forward cover may be booked up to the earlier of the expected realisation date or 12 months from the contract date. Rollover is permitted once against documentary "
        "evidence of a shipment delay.",
    },
    {
        "key": "fees",
        "source": "Product fee schedules",
        "title": "Schedule of charges — NRE / NRO",
        "section": "Account maintenance fees",
        "owner": "Retail Ops",
        "dept": "Retail Service Desk",
        "status": "stale",
        "verifiedDaysAgo": 94,
        "body": "Annual maintenance charges for NRE and NRO accounts as per the schedule effective 1 April. Card annual fees are levied on the card anniversary and reversed on request for the first year "
        "where spend exceeds the waiver threshold.",
    },
    {
        "key": "stm",
        "source": "Ops Confluence",
        "title": "Statement services SOP",
        "section": "§1.3 Re-issue on request",
        "owner": "Retail Ops",
        "dept": "Retail Service Desk",
        "status": "approved",
        "verifiedDaysAgo": 30,
        "body": "Statements may be re-issued to the registered email address only. Password-free copies may be issued on request. The first re-issue request in a financial year is free of charge.",
    },
    {
        "key": "dsp",
        "source": "Compliance circulars",
        "title": "Card Disputes Handling Note 2026-07",
        "section": "Provisional credit window",
        "owner": "Compliance",
        "dept": "Chargeback & Disputes",
        "status": "approved",
        "verifiedDaysAgo": 3,
        "body": 'Provisional credit for a valid disputed card transaction must be posted within 5 working days of the dispute being raised. Staff must not promise credit "within about a week".',
    },
    {
        "key": "swift",
        "source": "Ops Confluence",
        "title": "SWIFT trace procedure",
        "section": "§3 gpi tracker",
        "owner": "Trade & Payments",
        "dept": "Trade & Payments",
        "status": "approved",
        "verifiedDaysAgo": 15,
        "body": "Outward remittance status can be traced through the SWIFT gpi tracker using the UETR. Customers are given the latest tracker status and, where funds are held at an intermediary, the "
        "expected credit date.",
    },
]

KSOURCES: list[Any] = [
    {
        "name": "Policy SharePoint",
        "kind": "SharePoint",
        "abbr": "SP",
        "docs": 212,
        "unit": "documents",
        "approved": 186,
        "syncMinAgo": 22,
        "syncNote": "",
        "health": "ok",
        "note": "Watching /Policies and /Circulars for changes",
    },
    {
        "name": "Ops Confluence",
        "kind": "Confluence",
        "abbr": "CF",
        "docs": 148,
        "unit": "pages",
        "approved": 96,
        "syncMinAgo": 60,
        "syncNote": "",
        "health": "ok",
        "note": "New page versions land as pending until re-approved",
    },
    {
        "name": "Product fee schedules",
        "kind": "Google Drive",
        "abbr": "GD",
        "docs": 34,
        "unit": "sheets",
        "approved": 31,
        "syncMinAgo": 2880,
        "syncNote": "Sync failing · auth expired 2d ago",
        "health": "bad",
        "note": "Token needs re-consent by the Drive owner",
    },
    {
        "name": "Compliance circulars",
        "kind": "Upload",
        "abbr": "UP",
        "docs": 58,
        "unit": "PDFs",
        "approved": 58,
        "syncMinAgo": 5760,
        "syncNote": "Manual uploads · last 4d ago",
        "health": "warn",
        "note": "The 1 July fee circular is still missing here",
    },
]

MAILBOXES: list[Any] = [
    {
        "address": "customercare@bank.example",
        "dept": "Retail Service Desk",
        "team": "Retail Service Desk",
        "perms": ["read", "label", "draft"],
        "vol": 1842,
        "state": "streaming",
    },
    {
        "address": "tradeops@bank.example",
        "dept": "Trade & Payments",
        "team": "Trade & Payments",
        "perms": ["read", "label", "draft"],
        "vol": 486,
        "state": "streaming",
    },
    {
        "address": "disputes@bank.example",
        "dept": "Chargeback & Disputes",
        "team": "Chargeback & Disputes",
        "perms": ["read", "label only"],
        "vol": 412,
        "state": "triage_only",
    },
    {
        "address": "nri.desk@bank.example",
        "dept": "Retail Service Desk",
        "team": "Retail Service Desk",
        "perms": ["read", "label", "draft"],
        "vol": 174,
        "state": "streaming",
    },
    {
        "address": "grievance@bank.example",
        "dept": None,
        "team": "Compliance",
        "perms": ["read only"],
        "vol": 38,
        "state": "observe",
    },
]

NOTIFS: list[Any] = [
    {
        "kind": "learning",
        "source": "Agent-raised",
        "title": "Provisional credit window is now 5 days",
        "body": "An RBI circular changed the provisional credit window for card disputes from 7 to 5 days. This affects every disputes conversation.",
        "course": "disputes",
        "urgent": True,
        "minAgo": 120,
    },
    {
        "kind": "learning",
        "source": "Compliance",
        "title": "New hard stop: vulnerable customer signals",
        "body": "Mentions of bereavement, serious illness or financial distress now suspend AI drafting and route straight to a person.",
        "course": "vulnerable",
        "urgent": True,
        "minAgo": 1440,
    },
    {
        "kind": "message",
        "source": "Knowledge team",
        "title": "FEMA Note 2026-03 is live",
        "body": "NRE joint-holder answers are approved again — confidence recovered to 0.88. Drafts cite the new note automatically.",
        "course": None,
        "urgent": False,
        "minAgo": 1500,
    },
    {
        "kind": "message",
        "source": "Agent-raised",
        "title": "1 July fee circular reflected",
        "body": "The stale schedule of charges was refreshed. The AI stopped down-weighting fee answers.",
        "course": None,
        "urgent": False,
        "minAgo": 4320,
    },
]

ORGS: list[Any] = [
    {
        "slug": "apex",
        "name": "Apex Bank",
        "short": "AB",
        "tint": "#4B4EC8",
        "bg": "#EDECF9",
        "plan": "Enterprise",
        "locale": "en-IN",
        "currency": "INR",
        "time_zone": "Asia/Kolkata",
        "status": "live",
    },
    {
        "slug": "meridian",
        "name": "Meridian Financial",
        "short": "MF",
        "tint": "#1B6B49",
        "bg": "#E9F2EE",
        "plan": "Pilot",
        "locale": "en-IN",
        "currency": "INR",
        "time_zone": "Asia/Kolkata",
        "status": "live",
    },
    {
        "slug": "northwind",
        "name": "Northwind Cooperative",
        "short": "NC",
        "tint": "#8A6413",
        "bg": "#F6EEDF",
        "plan": "Trial",
        "locale": "en-IN",
        "currency": "INR",
        "time_zone": "Asia/Kolkata",
        "status": "live",
    },
]

OPERATORS: list[Any] = [
    {"email": "owner@platform.example", "name": "Platform Owner", "role": "platform_owner"},
    {"email": "ops@platform.example", "name": "Ops Engineer", "role": "operator"},
    {"email": "support@platform.example", "name": "Support Analyst", "role": "support"},
]

PEOPLE: list[Any] = [
    {
        "email": "p.sharma@bank.example",
        "name": "P. Sharma",
        "full": "Priyanka Sharma",
        "role": "staff",
        "title": "Customer support staff",
        "pod": "Retail pod 1",
        "years": 3,
        "cap": 12,
        "avail": "available",
        "checkin": "Checked in 07:58",
        "cal": "Team huddle 14:30",
        "clear": {
            "Retail Service Desk": 2,
            "Retail Lending": 2,
            "Cards": 1,
            "Trade & Payments": 2,
            "Chargeback & Disputes": 2,
        },
    },
    {
        "email": "r.menon@bank.example",
        "name": "R. Menon",
        "full": "Rahul Menon",
        "role": "lead",
        "title": "Team lead · checker",
        "pod": "All pods",
        "years": 14,
        "cap": 8,
        "avail": "busy",
        "checkin": "Checked in 07:45",
        "cal": "Risk review until 12:00",
        "clear": {
            "Retail Service Desk": 3,
            "Trade & Payments": 3,
            "Chargeback & Disputes": 3,
            "Retail Lending": 3,
            "Cards": 3,
        },
    },
    {
        "email": "a.kapoor@bank.example",
        "name": "A. Kapoor",
        "full": "Anjali Kapoor",
        "role": "admin",
        "title": "Risk & Compliance",
        "pod": "Risk",
        "years": 9,
        "cap": 6,
        "avail": "available",
        "checkin": "Checked in 08:20",
        "cal": "Policy review 16:00",
        "clear": {
            "Retail Service Desk": 1,
            "Trade & Payments": 1,
            "Chargeback & Disputes": 1,
            "Retail Lending": 1,
            "Cards": 1,
        },
    },
    {
        "email": "a.fernandes@bank.example",
        "name": "A. Fernandes",
        "full": "Arun Fernandes",
        "role": "staff",
        "title": "Senior staff",
        "pod": "Retail pod 1",
        "years": 6,
        "cap": 12,
        "avail": "available",
        "checkin": "Checked in 08:02",
        "cal": "Free until 15:00",
        "clear": {"Retail Service Desk": 3, "Cards": 2, "Retail Lending": 1},
    },
    {
        "email": "s.qureshi@bank.example",
        "name": "S. Qureshi",
        "full": "Sana Qureshi",
        "role": "staff",
        "title": "Disputes specialist",
        "pod": "Disputes",
        "years": 8,
        "cap": 12,
        "avail": "busy",
        "checkin": "Checked in 08:10",
        "cal": "On calls until 13:00",
        "clear": {"Chargeback & Disputes": 3, "Cards": 3, "Retail Service Desk": 1},
    },
    {
        "email": "d.kulkarni@bank.example",
        "name": "D. Kulkarni",
        "full": "Deepak Kulkarni",
        "role": "staff",
        "title": "Trade officer",
        "pod": "Trade & Payments",
        "years": 11,
        "cap": 12,
        "avail": "available",
        "checkin": "Checked in 08:31",
        "cal": "Free all day",
        "clear": {"Trade & Payments": 3, "Retail Service Desk": 1},
    },
    {
        "email": "l.thomas@bank.example",
        "name": "L. Thomas",
        "full": "Leena Thomas",
        "role": "staff",
        "title": "Lending officer",
        "pod": "Lending",
        "years": 5,
        "cap": 12,
        "avail": "away",
        "checkin": "On break · back 12:15",
        "cal": "Leave tomorrow",
        "clear": {"Retail Lending": 3, "Chargeback & Disputes": 2},
    },
]

PRIORITY_RULES: list[Any] = [
    {
        "key": "p1",
        "description": "Regulator, ombudsman or legal notice named",
        "target": "P1 · Critical",
        "hard": True,
        "hits": "9 this week",
    },
    {
        "key": "p2",
        "description": "Deadline inside 2 hours",
        "target": "P1 · Critical",
        "hard": True,
        "hits": "14 this week",
    },
    {
        "key": "p3",
        "description": "Amount at stake ≥ ₹10,00,000",
        "target": "At least P2 · High",
        "hard": False,
        "hits": "22 this week",
    },
    {
        "key": "p4",
        "description": "Third or later contact on the same matter",
        "target": "At least P2 · High",
        "hard": False,
        "hits": "31 this week",
    },
    {
        "key": "p5",
        "description": "Deadline inside 8 hours",
        "target": "At least P2 · High",
        "hard": False,
        "hits": "58 this week",
    },
    {
        "key": "p6",
        "description": "Vulnerable-customer signal on the thread",
        "target": "P1 + hard stop on AI drafting",
        "hard": True,
        "hits": "3 this week",
    },
    {
        "key": "p7",
        "description": "Informational, no deadline pressure",
        "target": "P4 · Low",
        "hard": False,
        "hits": "804 this week",
    },
]

QUERY_TYPES: list[Any] = [
    {
        "name": "Statement re-issue",
        "dept": "Retail Service Desk",
        "lane": "auto",
        "vol": 612,
        "live": True,
        "map": True,
        "speed": True,
        "base": 9.2,
        "act": 0.4,
        "late": 0,
        "owner": "Retail Ops",
    },
    {
        "name": "Balance & charge queries",
        "dept": "Retail Service Desk",
        "lane": "draft",
        "vol": 884,
        "live": True,
        "map": True,
        "speed": True,
        "base": 14,
        "act": 1.2,
        "late": 0,
        "owner": "Retail Ops",
    },
    {
        "name": "Account maintenance",
        "dept": "Retail Service Desk",
        "lane": "draft",
        "vol": 395,
        "live": True,
        "map": True,
        "speed": True,
        "base": 22.4,
        "act": 4.6,
        "late": 1,
        "owner": "Retail Ops",
    },
    {
        "name": "Certificate requests",
        "dept": "Retail Service Desk",
        "lane": "auto",
        "vol": 203,
        "live": True,
        "map": True,
        "speed": False,
        "base": None,
        "act": None,
        "late": 0,
        "owner": "Retail Ops",
    },
    {
        "name": "Locker rent waiver",
        "dept": None,
        "lane": "manual",
        "vol": 19,
        "live": False,
        "map": True,
        "speed": False,
        "base": None,
        "act": None,
        "late": 0,
        "owner": "Unassigned",
        "mapDept": "Retail Service Desk",
    },
    {
        "name": "Stop payment instruction",
        "dept": "Trade & Payments",
        "lane": "auto",
        "vol": 148,
        "live": True,
        "map": True,
        "speed": True,
        "base": 6.1,
        "act": 1.9,
        "late": 0,
        "owner": "Payments",
    },
    {
        "name": "Outward remittance",
        "dept": "Trade & Payments",
        "lane": "manual",
        "vol": 96,
        "live": True,
        "map": True,
        "speed": False,
        "base": None,
        "act": None,
        "late": 0,
        "owner": "Trade & Payments",
    },
    {
        "name": "Trade finance advisory",
        "dept": "Trade & Payments",
        "lane": "draft",
        "vol": 121,
        "live": False,
        "map": True,
        "speed": True,
        "base": 26.8,
        "act": 12.1,
        "late": 1,
        "owner": "Trade Fin.",
        "mapName": "Forward cover advisory",
    },
    {
        "name": "SWIFT trace requests",
        "dept": "Trade & Payments",
        "lane": "draft",
        "vol": 77,
        "live": True,
        "map": True,
        "speed": False,
        "base": None,
        "act": None,
        "late": 0,
        "owner": "Trade & Payments",
    },
    {
        "name": "Disputed transactions",
        "dept": "Chargeback & Disputes",
        "lane": "manual",
        "vol": 208,
        "live": False,
        "map": True,
        "speed": True,
        "base": 38.5,
        "act": 31.2,
        "late": 2,
        "owner": "Disputes",
    },
    {
        "name": "Chargeback status",
        "dept": "Chargeback & Disputes",
        "lane": "draft",
        "vol": 164,
        "live": False,
        "map": True,
        "speed": False,
        "base": None,
        "act": None,
        "late": 0,
        "owner": "Disputes",
    },
    {
        "name": "Provisional credit",
        "dept": "Chargeback & Disputes",
        "lane": "manual",
        "vol": 188,
        "live": True,
        "map": True,
        "speed": False,
        "base": None,
        "act": None,
        "late": 0,
        "owner": "Disputes",
    },
    {
        "name": "Fraud reporting",
        "dept": "Chargeback & Disputes",
        "lane": "manual",
        "vol": 52,
        "live": True,
        "map": True,
        "speed": False,
        "base": None,
        "act": None,
        "late": 0,
        "owner": "Disputes",
    },
    {
        "name": "Foreclosure quotes",
        "dept": "Retail Lending",
        "lane": "auto",
        "vol": 176,
        "live": True,
        "map": True,
        "speed": True,
        "base": 29.1,
        "act": 22.4,
        "late": 0,
        "owner": "Lending",
        "speedName": "Lending & foreclosure",
        "speedLane": "manual",
    },
    {
        "name": "EMI reschedule requests",
        "dept": "Retail Lending",
        "lane": "manual",
        "vol": 88,
        "live": True,
        "map": True,
        "speed": False,
        "base": None,
        "act": None,
        "late": 0,
        "owner": "Lending",
    },
    {
        "name": "Interest certificate",
        "dept": "Retail Lending",
        "lane": "auto",
        "vol": 134,
        "live": True,
        "map": True,
        "speed": False,
        "base": None,
        "act": None,
        "late": 0,
        "owner": "Lending",
    },
    {
        "name": "Credit limit explanations",
        "dept": "Retail Lending",
        "lane": "manual",
        "vol": 61,
        "live": True,
        "map": True,
        "speed": False,
        "base": None,
        "act": None,
        "late": 0,
        "owner": "Lending",
    },
    {
        "name": "Multi-intent — lending + cards",
        "dept": "Retail Lending",
        "lane": "manual",
        "vol": 0,
        "live": True,
        "map": False,
        "speed": False,
        "base": None,
        "act": None,
        "late": 0,
        "owner": "Lending",
    },
]

SERIES: dict[str, Any] = {
    "fr": [42, 40, 37, 33, 30, 26, 22, 19, 16, 14, 12, 11],
    "tat": [19, 18, 17, 15, 13, 11, 9, 8, 7, 6, 5.4, 5.1],
    "missed": [26, 24, 21, 19, 15, 13, 11, 9, 7, 6, 5, 4],
    "reopen": [1.4, 1.5, 1.6, 1.5, 1.7, 1.8, 1.7, 1.9, 2, 1.9, 2, 2.1],
    "accept": [58, 61, 63, 66, 68, 70, 73, 74, 75, 77, 77, 78],
    "auto": [9, 12, 14, 17, 19, 21, 24, 26, 27, 29, 30, 31],
    "csat": [3.7, 3.8, 3.8, 3.9, 4, 4, 4.1, 4.1, 4.2, 4.2, 4.3, 4.3],
    "cost": [0.95, 0.9, 0.86, 0.84, 0.8, 0.77, 0.72, 0.69, 0.66, 0.64, 0.63, 0.61],
    "awo": [9, 8, 10, 7, 8, 6, 7, 6, 5, 6, 5, 6],
    "execBaseline": [19.2, 18.8, 19.4, 18.1, 18.6, 19, 18.3, 17.9, 18.5, 18.2, 18.7, 18, 18.4, 18.4],
    "execActual": [12.1, 10.4, 9.6, 8.8, 8.1, 7.4, 7, 6.6, 6.2, 5.9, 5.6, 5.4, 5.2, 5.1],
}
