"""GENERATED by scripts/gen_dto.py from packages/contracts/src/dto.ts. Do not edit by hand."""

from __future__ import annotations

from typing import Any, Literal

from pydantic import Field

from command_inbox.schemas.base import CamelModel
from command_inbox.schemas.enums import (
    ActionState,
    AgentState,
    AgentTemplate,
    ApprovalChain,
    ApprovalMode,
    Availability,
    BoardState,
    Capability,
    ClearanceLevel,
    CommentKind,
    ConnectorState,
    DeploymentVersionState,
    DraftState,
    EvalRunState,
    EvalSplit,
    FeedbackKind,
    FixKind,
    GapSeverity,
    Health,
    InvitationState,
    KnowledgeKind,
    KpiMetric,
    Lane,
    MailboxState,
    MailProvider,
    NotificationKind,
    OwnerKind,
    PolicyEffect,
    Priority,
    RejectReason,
    RiskCell,
    Role,
    Segment,
    SlaTone,
    SpanStatus,
    TicketStatus,
)
from command_inbox.schemas.requests import FilterKey, TicketFilters

# ruff: noqa: F401

WorkspaceStatus = Literal[
    "draft",
    "provisioning",
    "provisioned",
    "onboarding",
    "shadow",
    "assisted",
    "live",
    "suspended",
    "archived",
]
GateMode = Literal["action", "draft", "manual"]
GateState = Literal["open", "awaiting_checker", "scheduled", "executing", "done", "rejected", "taken"]
ApproveOutcome = Literal["awaiting_checker", "scheduled", "sending", "taken"]
MailConnection = Literal[
    "not_connected", "connecting", "syncing", "live", "degraded", "reauth_required", "disconnected"
]
HealthLevel = Literal["healthy", "degraded", "down", "unknown"]
KnowledgeDocStatus = Literal["pending", "approved", "rejected", "retired", "stale"]
KnowledgeParseStatus = Literal["none", "queued", "scanning", "parsing", "ready", "failed", "infected"]
ModelProviderKey = Literal["anthropic", "openai"]
PilotStage = Literal["onboarding", "shadow", "assisted", "live"]
PilotGateState = Literal["pass", "fail", "pending"]
PilotRequestState = Literal["pending", "approved", "rejected", "withdrawn"]
IncidentSeverity = Literal["P1", "P2", "P3", "P4"]
IncidentKind = Literal["hard_stop_miss", "wrong_reply", "data_exposure", "outage", "other"]
FacetCounts = dict[str, dict[str, int | float]]


class UserRef(CamelModel):
    id: str
    name: str
    initials: str


class OrgDTO(CamelModel):
    id: str
    slug: str
    name: str
    short: str
    tint: str
    bg: str
    plan: str
    confidence_bar: int | float
    locale: str
    currency: str
    time_zone: str
    status: WorkspaceStatus


class WorkspaceProfileDTO(CamelModel):
    name: str
    legal_name: str
    support_email: str
    locale: str
    currency: str
    time_zone: str
    email_domains: list[str]
    region: str
    data_residency: str
    status: WorkspaceStatus
    sso: WorkspaceSsoDTO


class WorkspaceSsoDTO(CamelModel):
    provider: Literal["entra", "google"] | None
    directory_id: str
    client_id: str
    has_secret: bool
    state: Literal["not_connected", "saved", "connected", "failed"]
    detail: str
    idp_alias: str | None
    redirect_uri: str | None
    sso_members: int | float


class OnboardingStepDTO(CamelModel):
    key: str
    title: str
    description: str
    state: Literal["not_started", "in_progress", "done", "later"]
    detail: str
    to: str | None


class OnboardingDTO(CamelModel):
    status: WorkspaceStatus
    steps: list[OnboardingStepDTO]
    done: int | float
    total: int | float


class MembershipDTO(CamelModel):
    org: OrgDTO
    role: Role
    boards: int | float
    people: int | float
    unread: int | float


class NavCounts(CamelModel):
    inbox: int | float
    tickets: int | float
    boards: int | float
    alerts: int | float
    learning: int | float
    agents: int | float
    gaps: int | float
    autonomous_cells: int | float


class SettingsDTO(CamelModel):
    prefs: dict[str, bool]
    signature: str


class MeDTOUser(UserRef):
    email: str
    title: str
    pod: str
    joined_at: str


class MeDTOWorker(CamelModel):
    state: Literal["live", "degraded", "paused"]
    provider: Literal["claude", "openai", "heuristic"]


class MeDTOFeatures(CamelModel):
    telephony: bool


class MeDTO(CamelModel):
    user: MeDTOUser
    org: OrgDTO
    role: Role
    capabilities: list[Capability]
    memberships: list[MembershipDTO]
    csrf_token: str
    demo_mode: bool
    settings: SettingsDTO
    nav: NavCounts
    worker: MeDTOWorker
    features: MeDTOFeatures


class DemoUserDTO(CamelModel):
    email: str
    name: str
    role: Role
    title: str


class OrgChoiceDTO(OrgDTO):
    role: Role | None
    boards: int | float
    people: int | float


class SlaDTO(CamelModel):
    tone: SlaTone
    minutes_left: int | float | None
    budget_minutes: int | float
    due_at: str | None


class TicketSummaryDTO(CamelModel):
    id: str
    number: str
    subject: str
    from_name: str
    from_initials: str
    bucket: str
    department_id: str | None
    department: str
    lane: Lane
    original_lane: Lane
    lane_note: str
    status: TicketStatus
    priority: Priority
    segment: str
    confidence: int | float
    received_at: str
    sla: SlaDTO
    assignee: UserRef | None
    owner_kind: OwnerKind
    next_move: str
    board_id: str | None
    board_name: str
    thread_count: int | float
    pending_gate: Literal["maker", "checker", "send"] | None


class EvidenceDTO(CamelModel):
    tag: str
    quote: str
    why: str


class TriageDTO(CamelModel):
    reasoning: str
    evidence: list[EvidenceDTO]
    confidence: int | float
    latency_ms: int | float
    provider: str
    classified_at: str


class ActionFieldDTO(CamelModel):
    label: str
    value: str
    source: str
    inferred: bool


class ActionDTODuplicate(CamelModel):
    clear: bool
    text: str


class ActionDTO(CamelModel):
    id: str
    template_code: str
    name: str
    system: str
    endpoint: str
    reversible: bool
    money_moves: bool
    cell: RiskCell
    chain: ApprovalChain
    fields: list[ActionFieldDTO]
    validation: str
    state: ActionState
    maker: UserRef | None
    maker_at: str | None
    checker: UserRef | None
    checker_at: str | None
    execute_after: str | None
    executed_at: str | None
    external_ref: str | None
    duplicate: ActionDTODuplicate


class CitationDTO(CamelModel):
    n: int | float
    doc_id: str
    doc: str
    section: str
    verified_at: str
    owner: str


class DraftDTO(CamelModel):
    id: str
    subject: str
    to: str
    original_body: str
    current_body: str
    citations: list[CitationDTO]
    flagged: list[str]
    state: DraftState
    send_after: str | None
    sent_at: str | None


class BriefDTOContext(CamelModel):
    label: str
    value: str


class BriefDTOSuggestions(CamelModel):
    label: str
    meta: str


class BriefDTO(CamelModel):
    why: str
    summary: str
    context: list[BriefDTOContext]
    suggestions: list[BriefDTOSuggestions]


class GateDTO(CamelModel):
    mode: GateMode
    chain: ApprovalChain | None
    state: GateState
    maker: UserRef | None
    checker: UserRef | None
    proposed_checker: UserRef | None
    owner: UserRef | None
    customer_waiting_minutes: int | float | None
    reversible: bool | None
    money_moves: bool | None
    duplicate_clear: bool | None
    can_approve: bool
    blocked_reason: str | None
    can_undo: bool
    undo_until: str | None
    note: str | None


class MessageDTO(CamelModel):
    id: str
    direction: Literal["inbound", "outbound", "note"]
    from_name: str
    from_addr: str
    to_addr: str
    body: str
    sent_at: str


class SubtaskDTO(CamelModel):
    key: str
    label: str
    owner: str
    done: bool


class LogEntryDTO(CamelModel):
    id: str
    kind: CommentKind
    author_name: str
    author_initials: str
    body: str
    at: str


class SpanDTO(CamelModel):
    seq: int | float
    offset_ms: int | float
    agent: str
    model: str
    action: str
    output: str
    latency_ms: int | float
    tokens: int | float | None
    cost_minor: int | float | None
    status: SpanStatus


class TraceDTO(CamelModel):
    trace_id: str
    total_ms: int | float
    cost_minor: int | float
    spans: list[SpanDTO]


class LinkDTO(CamelModel):
    kind: str
    label: str
    ref: str | None


class AttachmentDTO(CamelModel):
    id: str
    ext: str
    name: str
    size: str


class PastTicketDTO(CamelModel):
    number: str
    subject: str
    at: str
    outcome: str
    tone: Literal["ok", "warn", "bad"]
    same_topic: bool


class CustomerDTO(CamelModel):
    id: str
    cif: str | None
    name: str
    email: str
    since_year: int | float | None
    segment: str
    account: str
    history: list[PastTicketDTO]


class TicketDetailDTOPermissions(CamelModel):
    can_work: bool
    can_assign: bool
    can_override_up: bool
    can_reply: bool


class TicketDetailDTO(TicketSummaryDTO):
    version: int | float
    from_email: str
    mailbox: str
    category: str
    subcategory: str
    product: str
    regulatory_flag: str | None
    reopen_count: int | float
    first_reply_at: str | None
    resolved_at: str | None
    split_proposed: bool
    messages: list[MessageDTO]
    triage: TriageDTO | None
    action: ActionDTO | None
    draft: DraftDTO | None
    brief: BriefDTO | None
    gate: GateDTO
    trace: TraceDTO | None
    subtasks: list[SubtaskDTO]
    log: list[LogEntryDTO]
    watchers: list[UserRef]
    watching: bool
    attachments: list[AttachmentDTO]
    links: list[LinkDTO]
    customer: CustomerDTO | None
    logged_minutes: int | float
    allowed_transitions: list[TicketStatus]
    permissions: TicketDetailDTOPermissions


class TicketListDTOStats(CamelModel):
    open: int | float
    awaiting_decision: int | float
    ai_owned: int | float
    at_risk: int | float
    closed_today: int | float


class TicketListDTOBoards(CamelModel):
    id: str
    key: str
    name: str
    source: str
    state: BoardState
    count: int | float


class TicketListDTODepartments(CamelModel):
    id: str
    name: str


class TicketListDTO(CamelModel):
    items: list[TicketSummaryDTO]
    total: int | float
    all: int | float
    facets: dict[str, dict[str, int | float]]
    stats: TicketListDTOStats
    boards: list[TicketListDTOBoards]
    buckets: list[str]
    departments: list[TicketListDTODepartments]


class NlFilterDTOChips(CamelModel):
    key: FilterKey
    value: str
    text: str


class NlFilterDTO(CamelModel):
    filters: TicketFilters
    chips: list[NlFilterDTOChips]
    understood: bool
    provider: str


class InboxDTOCounts(CamelModel):
    all: int | float
    auto: int | float
    draft: int | float
    manual: int | float
    late: int | float


class InboxDTO(CamelModel):
    items: list[TicketSummaryDTO]
    counts: InboxDTOCounts


class ActivityDTO(CamelModel):
    id: str
    text: str
    meta: str
    tone: Literal["ok", "stop", "flag", "info", "muted"]
    at: str
    ticket_number: str | None


class ShiftDTO(CamelModel):
    closed_today: int | float
    sent_as_drafted_pct: int | float
    saved_minutes: int | float
    missed_deadlines: int | float


class CallDTOTranscript(CamelModel):
    who: Literal["You", "Customer"]
    text: str


class CallDTO(CamelModel):
    id: str
    ticket_id: str
    state: Literal["dialing", "live", "wrap", "saved", "discarded"]
    started_at: str
    duration_sec: int | float
    number: str
    customer_name: str
    customer_initials: str
    transcript: list[CallDTOTranscript]
    script_length: int | float
    summary: str | None
    updates: list[str]
    recording: str | None


class BoardDTOAgents(CamelModel):
    id: str
    name: str


class BoardDTO(CamelModel):
    id: str
    key: str
    name: str
    source: str
    provider: MailProvider
    volume24h: int | float = Field(alias="volume24h")
    open: int | float
    auto_rate_pct: int | float
    state: BoardState
    team: str
    agents: list[BoardDTOAgents]


class AgentEvalDTO(CamelModel):
    label: str
    value: str
    tone: Literal["ok", "warn", "neutral"]


class CalibrationBandDTO(CamelModel):
    band: str
    predicted: int | float
    observed: int | float | None
    n: int | float


class AgentDTOBoards(CamelModel):
    id: str
    name: str


class AgentDTOVersions(CamelModel):
    version: int | float
    model: str
    created_at: str
    created_by: str
    eval_status: str


class AgentDTO(CamelModel):
    id: str
    name: str
    abbr: str
    template: AgentTemplate
    model: str
    state: AgentState
    version: int | float
    prompt: str
    eval_score: int | float | None
    cost_per1k_minor: int | float = Field(alias="costPer1kMinor")
    boards: list[AgentDTOBoards]
    evals: list[AgentEvalDTO]
    calibration: list[CalibrationBandDTO]
    versions: list[AgentDTOVersions]


class FeedbackDTO(CamelModel):
    id: str
    agent_name: str
    ticket_number: str | None
    kind: FeedbackKind
    text: str
    fix: FixKind
    status: Literal["open", "queued"]
    at: str


class AgentTemplateDTO(CamelModel):
    key: AgentTemplate
    label: str
    abbr: str
    what: str
    prompt: str
    recommended_model: str


class AgentsOverviewDTOModels(CamelModel):
    id: str
    note: str


class AgentsOverviewDTO(CamelModel):
    agents: list[AgentDTO]
    spend_month_minor: int | float
    feedback: list[FeedbackDTO]
    templates: list[AgentTemplateDTO]
    models: list[AgentsOverviewDTOModels]


class StaffDTO(CamelModel):
    id: str
    name: str
    initials: str
    role: Role
    title: str
    pod: str
    years: int | float
    open: int | float
    capacity: int | float
    availability: Availability
    checkin: str
    calendar: str
    clearances: dict[str, int | float]
    is_me: bool


class PeopleDTODepartments(CamelModel):
    id: str
    name: str


class PeopleDTO(CamelModel):
    staff: list[StaffDTO]
    departments: list[PeopleDTODepartments]
    editable: bool


class AutoAssignResultDTOMoves(CamelModel):
    ticket_number: str
    priority: Priority
    minutes_left: int | float | None
    to: str | None
    reason: str


class AutoAssignResultDTO(CamelModel):
    checked: int | float
    moves: list[AutoAssignResultDTOMoves]


class KpiTileDTO(CamelModel):
    key: str
    label: str
    value: str
    unit: str
    trend_pct: str
    trend_good: bool
    spark: list[int | float]
    digest: str
    tone: Literal["neutral", "bad"]


class QueryTypeSpeedDTO(CamelModel):
    id: str
    name: str
    department: str
    lane: Lane
    volume: int | float
    baseline_hours: int | float
    actual_hours: int | float
    late: int | float
    owner: str


class AlertDTO(CamelModel):
    id: str
    sev_label: str
    sev_kind: Literal["late", "pattern", "drift", "capacity", "health", "budget", "knowledge"]
    bucket: str
    text: str
    action_label: str
    owner: str
    at: str
    ref: str | None | None = None


class CustomKpiDTO(CamelModel):
    id: str
    name: str
    metric: KpiMetric
    metric_label: str
    viz: Literal["bars", "number"]
    scope: Literal["team", "me"]
    target: int | float
    current: int | float
    lower_is_better: bool
    on_track: bool
    spark: list[int | float]


class PerformanceDTOMetrics(CamelModel):
    key: KpiMetric
    label: str
    current: int | float


class PerformanceDTO(CamelModel):
    tiles: list[KpiTileDTO]
    query_types: list[QueryTypeSpeedDTO]
    alerts: list[AlertDTO]
    staff: list[StaffDTO]
    custom_kpis: list[CustomKpiDTO]
    metrics: list[PerformanceDTOMetrics]
    approve_without_open_pct: int | float


class ResultsDTODays(CamelModel):
    label: str
    baseline: int | float
    actual: int | float


class ResultsDTOCoverage(CamelModel):
    lane: Lane
    pct: int | float
    volume: int | float


class ResultsDTOPools(CamelModel):
    label: str
    metric: str
    note: str


class ResultsDTO(CamelModel):
    baseline_hours: int | float
    now_hours: int | float
    delta_pct: int | float
    capacity_multiple: int | float
    days: list[ResultsDTODays]
    coverage: list[ResultsDTOCoverage]
    pools: list[ResultsDTOPools]


class ActionTemplateDTO(CamelModel):
    id: str
    code: str
    name: str
    system: str
    owner: str
    approval: ApprovalMode
    stp_pct: int | float | None
    volume: int | float
    cell: RiskCell
    state: Literal["active", "suggest_only", "pending_review"]


class RiskCellDTO(CamelModel):
    cell: RiskCell
    title: str
    count: int | float
    dial: int | float
    locked: bool
    phase: str
    audit: str
    gate_note: str


class ActionsDTO(CamelModel):
    cells: list[RiskCellDTO]
    templates: list[ActionTemplateDTO]
    autonomous_cells: int | float


class PoliciesDTOBucketRules(CamelModel):
    id: str
    description: str
    target: str
    kind: str
    hits: str


class PoliciesDTOPriorityRules(CamelModel):
    id: str
    key: str
    description: str
    target: str
    hard: bool
    enabled: bool
    hits: str


class PoliciesDTOMatrixRows(CamelModel):
    capability: str
    values: list[Literal["yes", "no", "appr", "cell", "auto"]]


class PoliciesDTOMatrix(CamelModel):
    cols: list[str]
    rows: list[PoliciesDTOMatrixRows]


class PoliciesDTOCycles(CamelModel):
    cell: str
    chain: list[str]
    note: str


class PoliciesDTOProposedRules(CamelModel):
    id: str
    text: str
    ticket_number: str | None
    proposed_by: str
    at: str
    status: str


class PoliciesDTO(CamelModel):
    bucket_rules: list[PoliciesDTOBucketRules]
    priority_rules: list[PoliciesDTOPriorityRules]
    matrix: PoliciesDTOMatrix
    cycles: list[PoliciesDTOCycles]
    proposed_rules: list[PoliciesDTOProposedRules]


class KnowledgeSourceDTO(CamelModel):
    id: str
    name: str
    kind: str
    abbr: str
    docs: str
    approved: str
    sync: str
    health: Health
    note: str


class GapDTO(CamelModel):
    id: str
    number: str
    severity: GapSeverity
    question: str
    detail: str
    hits: int | float
    age: str
    owner: str
    state: str
    cta: str


class KnowledgeDTOReadiness(CamelModel):
    department: str
    pct: int | float
    note: str


class KnowledgeDTOHonest(CamelModel):
    quotable_pct: int | float
    ungrounded_sentences: int | float
    open_gaps: int | float


class KnowledgeDTO(CamelModel):
    sources: list[KnowledgeSourceDTO]
    readiness: list[KnowledgeDTOReadiness]
    honest: KnowledgeDTOHonest
    gaps: list[GapDTO]


class TaxonomyDTODepartmentsQueryTypes(CamelModel):
    id: str
    name: str
    lane: Lane
    volume: int | float
    live: bool


class TaxonomyDTODepartments(CamelModel):
    id: str
    name: str
    owner: UserRef | None
    gap_note: str
    tone: Literal["normal", "risk"]
    query_types: list[TaxonomyDTODepartmentsQueryTypes]


class TaxonomyDTOContract(CamelModel):
    title: str
    text: str


class TaxonomyDTO(CamelModel):
    departments: list[TaxonomyDTODepartments]
    owned: int | float
    total: int | float
    contract: list[TaxonomyDTOContract]


class MailboxDTO(CamelModel):
    id: str
    address: str
    department: str
    permissions: list[str]
    volume24h: int | float = Field(alias="volume24h")
    state: MailboxState
    provider: MailProvider


class ConnectorDTO(CamelModel):
    id: str
    abbr: str
    name: str
    scope: str
    state: ConnectorState


class AdminDTO(CamelModel):
    mailboxes: list[MailboxDTO]
    connectors: list[ConnectorDTO]
    guardrails: list[str]


class NotificationDTO(CamelModel):
    id: str
    kind: NotificationKind
    source: str
    title: str
    body: str
    course_id: str | None
    urgent: bool
    read: bool
    at: str


class CourseDTOCards(CamelModel):
    title: str
    body: str


class CourseDTOQuiz(CamelModel):
    q: str
    options: list[str]
    correct: int | float


class CourseDTO(CamelModel):
    id: str
    key: str
    title: str
    minutes: int | float
    cards: list[CourseDTOCards]
    quiz: list[CourseDTOQuiz]
    team_completion_pct: int | float
    completed_by_me: bool


class LearningDTO(CamelModel):
    notifications: list[NotificationDTO]
    unread: int | float
    courses: list[CourseDTO]
    team_size: int | float


class CopilotAnswerDTOActions(CamelModel):
    label: str
    filters: TicketFilters | None = None
    to: str | None = None


class CopilotAnswerDTO(CamelModel):
    headline: str
    lines: list[str]
    actions: list[CopilotAnswerDTOActions]
    provider: str


class SearchResultDTOTickets(CamelModel):
    id: str
    number: str
    subject: str
    lane: Lane


class SearchResultDTOCustomers(CamelModel):
    id: str
    cif: str | None
    name: str
    tickets: int | float
    latest_ticket_id: str | None


class SearchResultDTOKnowledge(CamelModel):
    id: str
    title: str
    section: str
    status: str


class SearchResultDTOPolicies(CamelModel):
    id: str
    text: str
    kind: str


class SearchResultDTO(CamelModel):
    tickets: list[SearchResultDTOTickets]
    customers: list[SearchResultDTOCustomers]
    knowledge: list[SearchResultDTOKnowledge]
    policies: list[SearchResultDTOPolicies]


class SessionDTO(CamelModel):
    id: str
    device: str
    location: str
    last_seen_at: str
    current: bool


class AuditVerifyDTO(CamelModel):
    ok: bool
    events: int | float
    broken_at: int | float | None


class ApproveResult(CamelModel):
    outcome: ApproveOutcome


class BatchApproveItem(CamelModel):
    ticket_id: str
    ok: bool
    outcome: ApproveOutcome | None | None = None
    error: str | None | None = None


class BatchApproveResult(CamelModel):
    results: list[BatchApproveItem]


class ReplyScheduled(CamelModel):
    reply_id: str
    send_after: str


class IngestResult(CamelModel):
    ticket_id: str
    number: int | float
    created: bool
    duplicate: bool


class AuthorizeUrlResult(CamelModel):
    authorize_url: str


class AssignResult(CamelModel):
    assignee: str
    reason: str


class EscalateResult(CamelModel):
    to: str


class SplitResult(CamelModel):
    children: list[str]


class PublishCheckDTO(CamelModel):
    ready: bool
    blockers: list[str]
    requires_single_admin_ack: bool
    eval_run_id: str | None


class DeploymentVersionDTO(CamelModel):
    id: str
    deployment_id: str
    version: int | float
    state: DeploymentVersionState
    canary_percent: int | float | None
    config_hash: str
    notes: str
    created_by: UserRef | None
    created_at: str
    edited_by: UserRef | None
    edited_at: str | None
    published_by: UserRef | None
    published_at: str | None
    retired_at: str | None
    eval_run_id: str | None
    config: dict[str, Any]
    publish_check: PublishCheckDTO | None


class DeploymentDTOCanary(CamelModel):
    version: int | float
    percent: int | float


class DeploymentDTOMailboxes(CamelModel):
    id: str
    address: str


class DeploymentDTO(CamelModel):
    id: str
    key: str
    name: str
    description: str
    status: Literal["active", "archived"]
    active_version_id: str | None
    active_version: int | float | None
    shadow_version: int | float | None
    canary: DeploymentDTOCanary | None
    draft_version_id: str | None
    mailboxes: list[DeploymentDTOMailboxes]
    created_at: str


class DeploymentDetailDTO(DeploymentDTO):
    versions: list[DeploymentVersionDTO]


class EvalDatasetDTOSplits(CamelModel):
    calibration: int | float
    test: int | float


class EvalDatasetDTO(CamelModel):
    id: str
    deployment_id: str | None
    name: str
    description: str
    cases: int | float
    splits: EvalDatasetDTOSplits
    snapshot: str
    created_at: str


class EvalCaseDTOInput(CamelModel):
    subject: str
    body: str
    from_email: str | None


class EvalCaseDTOExpected(CamelModel):
    category: str
    hard_stop: bool
    lane: Literal["draft", "manual"] | None | None = None
    draft_acceptable: bool | None | None = None


class EvalCaseDTO(CamelModel):
    id: str
    dataset_id: str
    input: EvalCaseDTOInput
    expected: EvalCaseDTOExpected
    split: EvalSplit
    tags: list[str]
    source: str
    ticket_id: str | None
    created_at: str


class EvalMetricsDTO(CamelModel):
    cases: int | float
    calibration_cases: int | float
    accuracy: int | float | None
    macro_f1: int | float | None
    hard_stop_recall: int | float | None
    ece: int | float | None
    ece_uncalibrated: int | float | None
    selective_accuracy: int | float | None
    coverage: int | float | None
    conformal_coverage: int | float | None
    lane_safety_violations: int | float
    escalation_rate: int | float | None
    p95_latency_ms: int | float | None
    cost_per_thousand_mails_minor: int | float | None
    temperature: int | float
    conformal_qhat: int | float | None
    system2_provider: str | None = None
    system2_models: list[str] | None = None
    adjudicated_cases: int | float | None = None
    adjudication_accuracy: int | float | None | None = None
    adjudication_unsure_rate: int | float | None | None = None
    end_to_end_accuracy: int | float | None | None = None
    drafts_scored: int | float | None = None
    grounded_draft_rate: int | float | None | None = None
    no_source_draft_rate: int | float | None | None = None
    system2_cost_minor: int | float | None = None
    system2_p95_latency_ms: int | float | None | None = None
    system2_fallbacks: int | float | None = None


class EvalGateDTO(CamelModel):
    key: str
    label: str
    metric: str
    op: Literal["gte", "lte"]
    threshold: int | float
    value: int | float | None
    passed: bool


class EvalRunDTOSplit(CamelModel):
    calibration: int | float
    test: int | float


class EvalRunDTO(CamelModel):
    id: str
    dataset_id: str
    dataset_name: str
    deployment_id: str
    deployment_version_id: str
    version: int | float
    state: EvalRunState
    engine: str
    config_hash: str
    dataset_snapshot: str
    current: bool
    provider: ModelProviderKey | None
    split: EvalRunDTOSplit
    metrics: EvalMetricsDTO | None
    gates: list[EvalGateDTO]
    passed: bool | None
    created_by: UserRef | None
    created_at: str
    started_at: str | None
    finished_at: str | None
    error: str | None


class EvalResultDTO(CamelModel):
    id: str
    case_id: str
    split: EvalSplit
    expected: str
    predicted: str
    confidence: int | float
    correct: bool
    hard_stop_expected: bool
    hard_stop_predicted: bool
    lane: Lane
    escalated: bool
    latency_ms: int | float


class MemberDTOUser(UserRef):
    email: str


class MemberDTO(CamelModel):
    user: MemberDTOUser
    role: Role
    title: str
    joined_at: str
    last_login_at: str | None
    is_me: bool


class InvitationDTO(CamelModel):
    id: str
    email: str
    role: Role
    state: InvitationState
    invited_by: UserRef | None
    created_at: str
    expires_at: str
    accepted_at: str | None
    revoked_at: str | None


class RolePolicyDTO(CamelModel):
    role: Role
    capability: Capability
    effect: PolicyEffect
    changed_by: UserRef | None
    changed_at: str


class PermissionMatrixDTORowsCells(CamelModel):
    role: Role
    allowed: bool
    baseline: bool
    override: PolicyEffect | None
    locked: bool


class PermissionMatrixDTORows(CamelModel):
    capability: Capability
    label: str
    delegable: bool
    admin_only: bool
    cells: list[PermissionMatrixDTORowsCells]


class PermissionMatrixDTO(CamelModel):
    roles: list[Role]
    rows: list[PermissionMatrixDTORows]
    overrides: list[RolePolicyDTO]


class ProblemDTO(CamelModel):
    type: str
    title: str
    status: int | float
    detail: str | None = None
    code: str
    request_id: str | None = None


class MailboxHealthSignalDTO(CamelModel):
    key: Literal["stream", "lag", "sweep", "credential", "send", "throttling"]
    label: str
    level: HealthLevel
    value: str


class MailSyncEventDTO(CamelModel):
    at: str
    kind: str
    ok: bool
    summary: str


class MailboxConnectionDTO(CamelModel):
    id: str
    address: str
    provider: MailProvider
    connection: MailConnection
    account: str | None
    mode: Literal["notifications", "polling"] | None
    send_enabled: bool
    level: HealthLevel
    signals: list[MailboxHealthSignalDTO]
    last_error: str
    last_error_at: str | None
    last_message_at: str | None
    last_test_at: str | None
    last_test_ok_at: str | None
    messages24h: int | float = Field(alias="messages24h")
    events: list[MailSyncEventDTO]


class MailConnectorsDTOProviders(CamelModel):
    microsoft: bool
    google: bool


class MailConnectorsDTO(CamelModel):
    providers: MailConnectorsDTOProviders
    webhooks: bool
    mailbox_limit: int | float
    mailboxes: list[MailboxConnectionDTO]


class KnowledgeDocumentDTO(CamelModel):
    id: str
    title: str
    filename: str
    version: int | float
    replaces_id: str | None
    status: KnowledgeDocStatus
    parse_status: KnowledgeParseStatus
    parse_error: str
    av_status: Literal["not_scanned", "clean", "infected", "error"]
    department_id: str | None
    department: str | None
    size: int | float
    chunk_count: int | float
    effective_from: str | None
    expires_at: str | None
    uploaded_by: str | None
    approved_by: str | None
    approved_at: str | None
    created_at: str
    can_approve: bool


class KnowledgeChunkDTO(CamelModel):
    id: str
    ordinal: int | float
    section: str
    page: int | float | None
    text: str
    tokens: int | float


class KnowledgeDocumentDetailDTO(KnowledgeDocumentDTO):
    chunks: list[KnowledgeChunkDTO]


class KnowledgeHitDTO(CamelModel):
    chunk_id: str
    doc_id: str
    title: str
    section: str
    page: int | float | None
    text: str
    score: int | float
    similarity: int | float
    text_match: bool


class KnowledgeSearchDTO(CamelModel):
    query: str
    hits: list[KnowledgeHitDTO]


class ModelProviderDTO(CamelModel):
    key: ModelProviderKey
    name: str
    configured: bool
    allowed: bool
    is_default: bool
    default_model: str
    spent_minor: int | float
    calls: int | float


class ModelPolicyDTO(CamelModel):
    providers: list[ModelProviderDTO]
    monthly_budget_minor: int | float | None
    spent_minor: int | float
    month: str
    budget_reached: bool
    can_edit: bool


class DepartmentAdminDTO(CamelModel):
    id: str
    name: str
    risk: bool
    owner: UserRef | None
    query_types: int | float
    open_tickets: int | float
    deletable: bool


class QueryTypeAdminDTO(CamelModel):
    id: str
    name: str
    department_id: str | None
    default_lane: Lane
    live: bool
    tickets: int | float
    deletable: bool


class TaxonomyAdminDTO(CamelModel):
    departments: list[DepartmentAdminDTO]
    query_types: list[QueryTypeAdminDTO]
    can_edit: bool


class SlaPolicyDTO(CamelModel):
    id: str
    name: str
    priority: Priority | None
    segment: str | None
    escalation: bool
    minutes: int | float


class SlaPoliciesDTO(CamelModel):
    policies: list[SlaPolicyDTO]
    using_defaults: bool
    segments: list[str]
    can_edit: bool


class BenchSpanDTO(CamelModel):
    agent: str
    model: str
    action: str
    output: str
    latency_ms: int | float
    tokens: int | float | None
    cost_minor: int | float | None
    status: SpanStatus


class BenchRunDTODraftCitations(CamelModel):
    n: int | float
    title: str
    section: str


class BenchRunDTODraft(CamelModel):
    body: str
    coverage: Literal["full", "partial", "none"]
    citations: list[BenchRunDTODraftCitations]
    flagged: list[str]


class BenchRunDTOBrief(CamelModel):
    summary: str


class BenchRunDTOFields(CamelModel):
    label: str
    value: str
    inferred: bool


class BenchRunDTO(CamelModel):
    version_id: str
    version: int | float
    state: DeploymentVersionState
    lane: Lane
    lane_note: str
    category: str | None
    confidence: int | float
    hard_stop: str | None
    draft: BenchRunDTODraft | None
    brief: BenchRunDTOBrief | None
    fields: list[BenchRunDTOFields]
    spans: list[BenchSpanDTO]
    cost_minor: int | float
    latency_ms: int | float
    degraded: list[str]


class BenchResultDTO(CamelModel):
    runs: list[BenchRunDTO]


class LabelCandidateDTOSuggested(CamelModel):
    category: str | None
    hard_stop: bool
    lane: Lane


class LabelCandidateDTO(CamelModel):
    ticket_id: str
    number: int | float
    subject: str
    body: str
    received_at: str
    suggested: LabelCandidateDTOSuggested


class LabellingQueueDTOCategories(CamelModel):
    key: str
    name: str


class LabellingQueueDTO(CamelModel):
    dataset_id: str
    categories: list[LabellingQueueDTOCategories]
    candidates: list[LabelCandidateDTO]
    labelled: int | float
    calibration: int | float
    test: int | float


class MonitoringCountDTO(CamelModel):
    key: str
    label: str
    count: int | float
    href: str | None


class NodeQualityDTO(CamelModel):
    agent: str
    model: str
    calls: int | float
    p50_ms: int | float | None
    p95_ms: int | float | None
    cost_minor: int | float
    flagged: int | float


class VersionQualityDTO(CamelModel):
    deployment: str
    version: int | float | None
    mails: int | float
    degraded_rate: int | float | None
    escalation_rate: int | float | None
    cost_per_mail_minor: int | float | None


class MonitoringDTOSlaByPriority(CamelModel):
    priority: Priority
    total: int | float
    breached: int | float


class MonitoringDTOSla(CamelModel):
    first_reply_median_min: int | float | None
    resolve_median_hours: int | float | None
    breached: MonitoringCountDTO
    at_risk: MonitoringCountDTO
    by_priority: list[MonitoringDTOSlaByPriority]


class MonitoringDTODraftsRejectReasons(CamelModel):
    reason: str
    count: int | float


class MonitoringDTODrafts(CamelModel):
    sent: int | float
    unedited: int | float
    edited: int | float
    discarded: int | float
    mean_edit_distance: int | float | None
    reject_reasons: list[MonitoringDTODraftsRejectReasons]


class MonitoringDTOSpend(CamelModel):
    month_minor: int | float
    cap_minor: int | float | None


class MonitoringDTOKnowledgeMostCited(CamelModel):
    doc_id: str
    title: str
    citations: int | float


class MonitoringDTOKnowledge(CamelModel):
    approved: int | float
    pending: int | float
    stale: int | float
    expiring_soon: int | float
    open_gaps: int | float
    most_cited: list[MonitoringDTOKnowledgeMostCited]


class MonitoringDTOMailboxes(CamelModel):
    id: str
    address: str
    level: str
    lag_seconds: int | float | None
    messages24h: int | float = Field(alias="messages24h")


class MonitoringDTO(CamelModel):
    days: int | float
    since: str
    funnel: list[MonitoringCountDTO]
    sla: MonitoringDTOSla
    drafts: MonitoringDTODrafts
    versions: list[VersionQualityDTO]
    nodes: list[NodeQualityDTO]
    spend: MonitoringDTOSpend
    knowledge: MonitoringDTOKnowledge
    mailboxes: list[MonitoringDTOMailboxes]
    open_alerts: int | float


class OperationsDTOSiem(CamelModel):
    url: str | None
    has_secret: bool
    delivered_seq: int | float
    pending: int | float
    last_ok_at: str | None
    last_error: str | None


class OperationsDTO(CamelModel):
    retention_mail_days: int | float | None
    retention_trace_days: int | float | None
    siem: OperationsDTOSiem
    audit_events: int | float
    can_edit: bool


class AuditManifestDTOFiles(CamelModel):
    name: str
    sha256: str
    bytes: int | float


class AuditManifestDTO(CamelModel):
    tenant: str
    generated_at: str
    since: str | None
    until: str | None
    events: int | float
    first_seq: int | float | None
    last_seq: int | float | None
    last_hash: str | None
    files: list[AuditManifestDTOFiles]
    signature: str


class ScimSettingsDTOGroups(CamelModel):
    name: str
    members: int | float


class ScimSettingsDTO(CamelModel):
    base_url: str
    enabled: bool
    token_created_at: str | None
    last_used_at: str | None
    group_roles: dict[str, Role]
    groups: list[ScimSettingsDTOGroups]
    provisioned_members: int | float
    can_edit: bool


class ScimTokenDTO(CamelModel):
    token: str
    settings: ScimSettingsDTO


class PilotGateDTO(CamelModel):
    key: str
    label: str
    state: PilotGateState
    value: str
    target: str


class PilotTargetsDTO(CamelModel):
    acceptance: int | float
    light_edit_max: int | float
    agreement: int | float
    shadow_days: int | float
    assisted_days: int | float
    min_labelled: int | float
    min_drafts: int | float


class PilotBaselineDTO(CamelModel):
    on_time_rate: int | float | None
    first_reply_minutes: int | float | None
    captured_at: str | None
    source: Literal["records", "manual"] | None
    days: int | float | None


class PilotKpisDTO(CamelModel):
    window_start: str
    days: int | float
    drafts_decided: int | float
    drafts_accepted: int | float
    acceptance_rate: int | float | None
    labelled: int | float
    category_agreement: int | float | None
    lane_compared: int | float
    lane_agreement: int | float | None
    hard_stop_misses: int | float
    on_time_rate: int | float | None
    median_first_reply_minutes: int | float | None
    p1_incidents: int | float
    open_incidents: int | float


class PilotRequestDTO(CamelModel):
    id: str
    from_stage: str
    to_stage: str
    reason: str
    state: PilotRequestState
    requested_by: UserRef | None
    requested_at: str
    decided_by: UserRef | None
    decided_at: str | None
    decision_note: str
    evidence: list[PilotGateDTO]
    can_decide: bool
    can_withdraw: bool


class PilotDTO(CamelModel):
    stage: WorkspaceStatus
    stage_since: str
    days_in_stage: int | float
    next: PilotStage | None
    gates: list[PilotGateDTO]
    ready: bool
    pending: PilotRequestDTO | None
    history: list[PilotRequestDTO]
    kpis: PilotKpisDTO
    targets: PilotTargetsDTO
    baseline: PilotBaselineDTO
    risk_approvers: list[UserRef]
    sends_allowed: bool
    can_request: bool
    can_step_back: bool
    can_edit_settings: bool


class ShadowReportDTOLanes(CamelModel):
    ai: str
    final: str
    count: int | float


class ShadowReportDTOCategories(CamelModel):
    key: str
    labelled: int | float
    agreed: int | float


class ShadowReportDTODisagreements(CamelModel):
    ticket_id: str
    number: int | float
    subject: str
    kind: Literal["category", "lane", "hard_stop_miss"]
    ai_category: str | None
    human_category: str | None
    ai_lane: str
    final_lane: str
    ai_hard_stop: str | None


class ShadowReportDTO(CamelModel):
    days: int | float
    compared: int | float
    labelled: int | float
    lanes: list[ShadowReportDTOLanes]
    categories: list[ShadowReportDTOCategories]
    disagreements: list[ShadowReportDTODisagreements]


class PilotIncidentDTO(CamelModel):
    id: str
    severity: IncidentSeverity
    kind: IncidentKind
    title: str
    detail: str
    ticket_id: str | None
    ticket_number: int | float | None
    opened_by: UserRef | None
    opened_at: str
    resolved_by: UserRef | None
    resolved_at: str | None
    resolution: str
