"""GENERATED by scripts/gen_dto.py from packages/contracts/src/enums.ts. Do not edit by hand."""

from typing import Literal

Role = Literal["staff", "lead", "admin"]
Lane = Literal["auto", "draft", "manual"]
TicketStatus = Literal[
    "triaging", "awaiting_approval", "executing", "with_human", "waiting_customer", "resolved", "closed"
]
Priority = Literal["P1", "P2", "P3", "P4"]
Segment = Literal["Retail", "Corporate", "SME", "NRI"]
SlaTone = Literal["on_track", "due_soon", "almost_late", "late", "paused", "closed"]
OwnerKind = Literal["ai", "user", "unassigned"]
ApprovalChain = Literal["auto", "single", "single_undo", "dual"]
ApprovalMode = Literal["auto", "single", "dual"]
ActionState = Literal[
    "drafted", "awaiting_checker", "scheduled", "executing", "executed", "failed", "cancelled", "rejected"
]
DraftState = Literal["draft", "scheduled", "sent", "recalled", "discarded"]
CommentKind = Literal["note", "public", "call", "system"]
SpanStatus = Literal["ok", "flag", "stop"]
Availability = Literal["available", "busy", "away"]
AgentTemplate = Literal["bucketing", "extraction", "drafting", "summarisation", "policy_guard"]
AgentState = Literal["observe", "live", "paused"]
FeedbackKind = Literal["override", "edit", "rejection"]
FixKind = Literal["prompt", "context"]
RejectReason = Literal["wrong_type", "bad_field", "tone", "needs_human"]
BoardState = Literal["live", "triage_only", "observe", "paused"]
MailProvider = Literal["microsoft", "google", "imap", "dev"]
MailboxState = Literal["streaming", "triage_only", "observe", "connecting", "error"]
Health = Literal["ok", "warn", "bad"]
GapSeverity = Literal["blocking", "stale", "unowned", "resolved"]
NotificationKind = Literal["message", "learning", "alert"]
KpiMetric = Literal["fr", "tat", "accept", "reopen", "auto", "csat", "cost", "awo"]
ConnectorState = Literal["connected", "read_only", "suggest_only", "error"]
KnowledgeKind = Literal["SharePoint", "Confluence", "Google Drive", "S3", "Upload"]
RiskCell = Literal["0-0", "0-1", "1-0", "1-1"]
Capability = Literal[
    "ticket.work",
    "ticket.reply",
    "ticket.assign",
    "ticket.override_up",
    "action.approve_maker",
    "action.approve_checker",
    "people.edit_clearance",
    "people.auto_assign",
    "insights.view",
    "kpi.manage",
    "learning.send",
    "setup.view",
    "setup.edit",
    "autonomy.change",
    "rules.edit",
    "audit.verify",
    "deployment.view",
    "deployment.edit",
    "deployment.publish",
    "evals.view",
    "evals.run",
    "members.manage",
    "rbac.manage",
    "workspace.manage",
]
DeploymentVersionState = Literal["draft", "shadow", "canary", "published", "retired"]
EvalRunState = Literal["queued", "running", "passed", "failed", "error"]
EvalSplit = Literal["calibration", "test"]
InvitationState = Literal["pending", "accepted", "revoked", "expired"]
PolicyEffect = Literal["allow", "deny"]
ClearanceLevel = Literal[0, 1, 2, 3]
