"""GENERATED by scripts/gen_dto.py from packages/contracts/src/platform-dto.ts. Do not edit by hand."""

from __future__ import annotations

from typing import Any, Literal

from pydantic import Field

from command_inbox.schemas.base import CamelModel
from command_inbox.schemas.enums import (
    ActionState,
    AgentState,
    AgentTemplate,
    ApprovalChain,
    ApprovalMode,
    Availability,
    BoardState,
    Capability,
    ClearanceLevel,
    CommentKind,
    ConnectorState,
    DeploymentVersionState,
    DraftState,
    EvalRunState,
    EvalSplit,
    FeedbackKind,
    FixKind,
    GapSeverity,
    Health,
    InvitationState,
    KnowledgeKind,
    KpiMetric,
    Lane,
    MailboxState,
    MailProvider,
    NotificationKind,
    OwnerKind,
    PolicyEffect,
    Priority,
    RejectReason,
    RiskCell,
    Role,
    Segment,
    SlaTone,
    SpanStatus,
    TicketStatus,
)
from command_inbox.schemas.requests import FilterKey, TicketFilters

# ruff: noqa: F401

TenantStatus = Literal[
    "draft",
    "provisioning",
    "provisioned",
    "onboarding",
    "shadow",
    "assisted",
    "live",
    "suspended",
    "archived",
]
OperatorRole = Literal["platform_owner", "operator", "support"]
PlatformCapability = Literal[
    "tenants.view", "tenants.create", "tenants.lifecycle", "tenants.invite", "audit.view", "operators.manage"
]
TenantAction = Literal["provision", "suspend", "resume", "archive", "reinvite"]
StepState = Literal["pending", "running", "done", "skipped", "failed"]


class OperatorDTO(CamelModel):
    id: str
    email: str
    name: str
    role: OperatorRole
    capabilities: list[PlatformCapability]


class PlatformMeDTO(CamelModel):
    operator: OperatorDTO
    csrf_token: str


class PlatformAuthConfigDTODevOperators(CamelModel):
    email: str
    name: str
    role: OperatorRole


class PlatformAuthConfigDTO(CamelModel):
    sso: bool
    dev_operators: list[PlatformAuthConfigDTODevOperators]


class TenantLimitsDTO(CamelModel):
    mailboxes: int | float
    seats: int | float
    monthly_mail: int | float
    model_spend_cap_minor: int | float
    storage_gb: int | float


class TenantSummaryDTO(CamelModel):
    id: str
    slug: str
    name: str
    legal_name: str
    status: TenantStatus
    region: str
    plan: str
    created_at: str
    status_changed_at: str
    members: int | float
    admins: int | float
    mailboxes: int | float
    provisioning: StepState | None


class ProvisioningStepDTO(CamelModel):
    step: str
    label: str
    state: StepState
    attempts: int | float
    detail: str
    updated_at: str


class TenantInvitationDTO(CamelModel):
    id: str
    email: str
    name: str
    role: Role
    state: Literal["pending", "accepted", "expired", "revoked"]
    created_at: str
    expires_at: str
    sent_at: str | None
    send_count: int | float
    invited_by: str


class TenantKeyDTO(CamelModel):
    version: int | float
    state: Literal["active", "retired", "destroyed"]
    kek_ref: str
    created_at: str


class PlatformAuditEventDTO(CamelModel):
    seq: int | float
    at: str
    operator_email: str
    action: str
    tenant_id: str | None
    summary: str
    data: dict[str, Any]


class TenantDetailDTO(TenantSummaryDTO):
    locale: str
    currency: str
    time_zone: str
    data_residency: str
    support_email: str
    email_domains: list[str]
    sso_idp_alias: str | None
    limits: TenantLimitsDTO
    keys: list[TenantKeyDTO]
    steps: list[ProvisioningStepDTO]
    invitations: list[TenantInvitationDTO]
    audit: list[PlatformAuditEventDTO]
    actions: list[TenantAction]


class PlatformAuditVerifyDTO(CamelModel):
    ok: bool
    events: int | float
    broken_at: int | float | None


class InvitationPreviewDTO(CamelModel):
    tenant_name: str
    email: str
    name: str
    role: Role
    invited_by: str
    expires_at: str
    state: Literal["pending", "accepted", "expired", "revoked"]
    sign_in: Literal["sso", "direct"]
    can_bootstrap: bool
