"""Tenant access control, SSO identity, mailbox deployments and evals.

Adds role overrides and invitations (one role per user per tenant is enforced by a CHECK), the identity
provider subject on users, versioned deployments bound to mailboxes, and eval datasets, runs and results.
Every new tenant table gets the same row-level security policy as the baseline.

Revision ID: 0002_deployments
Revises: 0001_baseline
Create Date: 2026-09-28 04:36:54.912222

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0002_deployments"
down_revision: str | Sequence[str] | None = "0001_baseline"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deployment_versions",
        sa.Column("id", sa.Uuid(as_uuid=False), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("deployment_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("state", sa.Text(), server_default=sa.text("'draft'::text"), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("notes", sa.Text(), server_default=sa.text("''::text"), nullable=False),
        sa.Column("created_by", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("published_by", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("eval_run_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.PrimaryKeyConstraint("id", name="deployment_versions_pkey"),
    )
    op.create_index(
        "deployment_versions_uq", "deployment_versions", ["org_id", "deployment_id", "version"], unique=True
    )
    op.create_table(
        "deployments",
        sa.Column("id", sa.Uuid(as_uuid=False), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), server_default=sa.text("''::text"), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'active'::text"), nullable=False),
        sa.Column("active_version_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("created_by", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name="deployments_pkey"),
    )
    op.create_index("deployments_org_key_uq", "deployments", ["org_id", "key"], unique=True)
    op.create_table(
        "eval_cases",
        sa.Column("id", sa.Uuid(as_uuid=False), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("dataset_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("input", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expected", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "tags",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("source", sa.Text(), server_default=sa.text("'manual'::text"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name="eval_cases_pkey"),
    )
    op.create_index("eval_cases_dataset_idx", "eval_cases", ["org_id", "dataset_id"], unique=False)
    op.create_table(
        "eval_datasets",
        sa.Column("id", sa.Uuid(as_uuid=False), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("deployment_id", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), server_default=sa.text("''::text"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name="eval_datasets_pkey"),
    )
    op.create_table(
        "eval_results",
        sa.Column("id", sa.Uuid(as_uuid=False), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("run_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("case_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("output", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("scores", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("trace_id", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="eval_results_pkey"),
    )
    op.create_index("eval_results_run_idx", "eval_results", ["org_id", "run_id"], unique=False)
    op.create_table(
        "eval_runs",
        sa.Column("id", sa.Uuid(as_uuid=False), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("dataset_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("deployment_version_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("state", sa.Text(), server_default=sa.text("'queued'::text"), nullable=False),
        sa.Column(
            "metrics",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "gates",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("engine", sa.Text(), server_default=sa.text("''::text"), nullable=False),
        sa.Column("created_by", sa.Uuid(as_uuid=False), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="eval_runs_pkey"),
    )
    op.create_index("eval_runs_version_idx", "eval_runs", ["org_id", "deployment_version_id"], unique=False)
    op.create_table(
        "invitations",
        sa.Column("id", sa.Uuid(as_uuid=False), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("invited_by", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name="invitations_pkey"),
    )
    op.create_index("invitations_org_email_uq", "invitations", ["org_id", "email"], unique=True)
    op.create_table(
        "role_policies",
        sa.Column("org_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("capability", sa.Text(), nullable=False),
        sa.Column("effect", sa.Text(), nullable=False),
        sa.Column("changed_by", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("changed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("org_id", "role", "capability", name="role_policies_pkey"),
    )
    op.add_column("mailboxes", sa.Column("deployment_id", sa.Uuid(as_uuid=False), nullable=True))
    op.add_column("tickets", sa.Column("deployment_id", sa.Uuid(as_uuid=False), nullable=True))
    op.add_column("tickets", sa.Column("deployment_version_id", sa.Uuid(as_uuid=False), nullable=True))
    op.add_column("users", sa.Column("idp_subject", sa.Text(), nullable=True))
    op.add_column("users", sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###
    op.create_check_constraint("memberships_role_ck", "memberships", "role in ('staff', 'lead', 'admin')")
    op.create_check_constraint("role_policies_effect_ck", "role_policies", "effect in ('allow', 'deny')")
    op.create_check_constraint("role_policies_role_ck", "role_policies", "role in ('staff', 'lead')")
    op.create_check_constraint("invitations_role_ck", "invitations", "role in ('staff', 'lead', 'admin')")
    op.create_check_constraint(
        "deployment_versions_state_ck", "deployment_versions", "state in ('draft', 'published', 'retired')"
    )
    op.create_index(
        "users_idp_subject_uq",
        "users",
        ["idp_subject"],
        unique=True,
        postgresql_where=sa.text("idp_subject is not null"),
    )
    op.create_index("tickets_deployment_idx", "tickets", ["org_id", "deployment_id"])
    for table in (
        "role_policies",
        "invitations",
        "deployments",
        "deployment_versions",
        "eval_datasets",
        "eval_cases",
        "eval_runs",
        "eval_results",
    ):
        op.execute(f"select ci_enable_tenant_rls('{table}')")
    # Tables created by the owner inherit the app role's grants via ALTER DEFAULT PRIVILEGES (baseline).


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_login_at")
    op.drop_column("users", "idp_subject")
    op.drop_column("tickets", "deployment_version_id")
    op.drop_column("tickets", "deployment_id")
    op.drop_column("mailboxes", "deployment_id")
    op.drop_table("role_policies")
    op.drop_index("invitations_org_email_uq", table_name="invitations")
    op.drop_table("invitations")
    op.drop_index("eval_runs_version_idx", table_name="eval_runs")
    op.drop_table("eval_runs")
    op.drop_index("eval_results_run_idx", table_name="eval_results")
    op.drop_table("eval_results")
    op.drop_table("eval_datasets")
    op.drop_index("eval_cases_dataset_idx", table_name="eval_cases")
    op.drop_table("eval_cases")
    op.drop_index("deployments_org_key_uq", table_name="deployments")
    op.drop_table("deployments")
    op.drop_index("deployment_versions_uq", table_name="deployment_versions")
    op.drop_table("deployment_versions")
    # ### end Alembic commands ###
