"""Generate Pydantic response models from the web app's TypeScript contracts.

The React app is typed by packages/contracts (dto.ts, enums.ts). The API must serialise exactly those
shapes, so the Python models are generated from them rather than kept in sync by hand:

    uv run python scripts/gen_dto.py   # writes src/command_inbox/schemas/dto.py and enums.py

CI runs this and fails if the output differs from what is committed.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

from pydantic.alias_generators import to_camel

ROOT = Path(__file__).resolve().parents[3]
CONTRACTS = ROOT / "packages" / "contracts" / "src"
OUT = Path(__file__).resolve().parents[1] / "src" / "command_inbox" / "schemas"

HEADER = '"""GENERATED by scripts/gen_dto.py from packages/contracts/src/{src}. Do not edit by hand."""\n\n'


def strip_comments(s: str) -> str:
    s = re.sub(r"/\*.*?\*/", "", s, flags=re.S)
    return re.sub(r"//[^\n]*", "", s)


def gen_enums() -> tuple[str, set[str]]:
    src = strip_comments((CONTRACTS / "enums.ts").read_text())
    names: set[str] = set()
    out = [HEADER.format(src="enums.ts"), "from typing import Literal\n\n"]
    for name, body in re.findall(r"export const (\w+) = z\.enum\(\[(.*?)\]\)", src, re.S):
        values = re.findall(r"'([^']*)'", body)
        out.append(f"{name} = Literal[{', '.join(repr(v) for v in values)}]\n")
        names.add(name)
    out.append("ClearanceLevel = Literal[0, 1, 2, 3]\n")
    names.add("ClearanceLevel")
    return "".join(out), names


class Gen:
    def __init__(self, enum_names: set[str]) -> None:
        self.enums = enum_names
        self.classes: list[str] = []
        self.aliases: list[str] = []
        self.known: set[str] = set()

    def split_top(self, s: str, sep: str) -> list[str]:
        parts, depth, cur = [], 0, ""
        for ch in s:
            if ch in "{(<[":
                depth += 1
            elif ch in "})>]":
                depth -= 1
            if ch == sep and depth == 0:
                parts.append(cur)
                cur = ""
            else:
                cur += ch
        parts.append(cur)
        return [p.strip() for p in parts if p.strip()]

    def type_of(self, t: str, owner: str, field: str) -> str:
        t = t.strip()
        union = self.split_top(t, "|")
        if len(union) > 1:
            lits = [u for u in union if re.fullmatch(r"'[^']*'", u)]
            rest = [u for u in union if u not in lits]
            parts = []
            if lits:
                parts.append(f"Literal[{', '.join(lits)}]")
            parts += [self.type_of(u, owner, field) for u in rest]
            return " | ".join(parts)
        inter = self.split_top(t, "&")
        if len(inter) > 1:
            base, extra = inter[0], inter[1]
            name = owner + field[:1].upper() + field[1:]
            return self.object_class(name, extra.strip()[1:-1], base)
        if t.endswith("[]"):
            return f"list[{self.type_of(t[:-2], owner, field)}]"
        if t.startswith("(") and t.endswith(")"):
            return self.type_of(t[1:-1], owner, field)
        if re.fullmatch(r"'[^']*'", t):
            return f"Literal[{t}]"
        if t.startswith("Partial<") and t.endswith(">"):
            return self.type_of(t[len("Partial<") : -1], owner, field)
        if t.startswith("Record<") and t.endswith(">"):
            _k, v = self.split_top(t[len("Record<") : -1], ",")
            return f"dict[str, {self.type_of(v, owner, field)}]"
        if t.startswith("{"):
            name = owner + field[:1].upper() + field[1:]
            return self.object_class(name, t[1:-1])
        return {
            "string": "str",
            "number": "int | float",
            "boolean": "bool",
            "null": "None",
            "unknown": "Any",
        }.get(t, t)

    def fields(self, body: str, owner: str) -> list[str]:
        lines = []
        for member in self.split_top(body, ";"):
            member = member.strip().rstrip(",")
            if not member:
                continue
            if member.startswith("["):  # index signature
                m = re.match(r"\[key: string\]: (.+)", member)
                lines.append(("__index__", self.type_of(m.group(1), owner, "value")))
                continue
            m = re.match(r"(\w+)(\?)?:\s*(.+)", member, re.S)
            if not m:
                raise ValueError(f"cannot parse member {member!r} in {owner}")
            name, opt, typ = m.group(1), m.group(2), " ".join(m.group(3).split())
            py = self.type_of(typ, owner, name)
            if opt:
                py = f"{py} | None = None"
            lines.append((name, py))
        return lines

    def object_class(self, name: str, body: str, base: str = "CamelModel") -> str:
        members = self.fields(body, name)
        if members and members[0][0] == "__index__":
            self.aliases.append(f"{name} = dict[str, {members[0][1]}]\n")
            return name
        out = [f"class {name}({base}):\n"]
        if not members:
            out.append("    pass\n")
        for field, typ in members:
            snake = re.sub(r"(?<!^)(?=[A-Z])", "_", field).lower()
            if to_camel(snake) == field:
                out.append(f"    {snake}: {typ}\n")
            elif typ.endswith(
                " = None"
            ):  # the alias generator would not round-trip (volume24h, costPer1kMinor)
                out.append(f'    {snake}: {typ[: -len(" = None")]} = Field(default=None, alias="{field}")\n')
            else:
                out.append(f'    {snake}: {typ} = Field(alias="{field}")\n')
        self.classes.append("".join(out) + "\n\n")
        self.known.add(name)
        return name

    def run(self) -> str:
        src = strip_comments((CONTRACTS / "dto.ts").read_text())
        for m in re.finditer(r"export type (\w+) =\s*([^;]+);", src):
            self.aliases.append(f"{m.group(1)} = {self.type_of(m.group(2), m.group(1), '')}\n")
        pos = 0
        pattern = re.compile(r"export interface (\w+)(?: extends (\w+))? \{")
        while (m := pattern.search(src, pos)) is not None:
            depth, i = 1, m.end()
            while depth:
                depth += {"{": 1, "}": -1}.get(src[i], 0)
                i += 1
            body = src[m.end() : i - 1]
            self.object_class(m.group(1), body, m.group(2) or "CamelModel")
            pos = i
        enum_import = ", ".join(sorted(self.enums))
        head = [
            HEADER.format(src="dto.ts"),
            "from __future__ import annotations\n\n",
            "from typing import Any, Literal\n\n",
            "from pydantic import Field\n\n",
            "from command_inbox.schemas.base import CamelModel\n",
            f"from command_inbox.schemas.enums import {enum_import}\n",
            "from command_inbox.schemas.requests import FilterKey, TicketFilters\n\n",
            "# ruff: noqa: F401\n\n",
        ]
        return "".join(head) + "".join(self.aliases) + "\n\n" + "".join(self.classes)


def _ruff(args: list[str], content: str, fname: str) -> str:
    out = subprocess.run(  # noqa: S603
        ["ruff", *args, "--stdin-filename", str(OUT / fname), "-"],  # noqa: S607
        input=content,
        capture_output=True,
        text=True,
        check=True,
    )
    return out.stdout


def _format(content: str, fname: str) -> str:
    """Sort imports and format like the checked-in files, so --check compares like with like."""
    return _ruff(
        ["format"], _ruff(["check", "--select", "I", "--fix-only", "--exit-zero"], content, fname), fname
    )


def main() -> int:
    enums, names = gen_enums()
    dto = Gen(names).run()
    check = "--check" in sys.argv
    changed = False
    for fname, raw in (("enums.py", enums), ("dto.py", dto)):
        content = _format(raw, fname)
        path = OUT / fname
        if check:
            if not path.exists() or path.read_text() != content:
                print(f"{path} is out of date; run scripts/gen_dto.py")
                changed = True
        else:
            path.write_text(content)
    return 1 if changed else 0


if __name__ == "__main__":
    sys.exit(main())
