"""Response-diff harness: replay the `/v1` GET corpus against the TS and the Python API and diff the answers.

    uv run python scripts/parity.py --start [--out parity-report.json]
    uv run python scripts/parity.py --ts-url http://127.0.0.1:4214 --py-url http://127.0.0.1:4114

With `--start` the harness seeds a source database with `command-inbox-seed` (clock pinned to the current
minute), clones it twice (`ci_parity_ts`, `ci_parity_py`) and starts both servers itself on ports 4214 (TS)
and 4114 (Python); it stops them when it is done. Without it, it targets servers that are already running
on two copies of the same seeded database.

Each demo user (staff, lead, admin) signs in on both servers with POST /v1/auth/login. The corpus covers
every GET route in apps/server/src/routes/*.ts; ids come from the TS responses (both databases are clones,
so ids agree). Volatile fields are normalised before diffing: CSRF tokens, request ids, session ids, and
timestamps that differ by under two seconds (created at sign-in, a moment apart on each server).

The report lists, per request, both status codes and the differing JSON paths, and a coverage summary per
route: identical, differing, or missing (the Python API answers 404/405 where the TS API does not).
"""

# ruff: noqa: S603, S607, S608 - a developer tool that runs fixed commands against local databases
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import time
from collections import defaultdict
from contextlib import ExitStack
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import httpx
import psycopg

API_DIR = Path(__file__).resolve().parents[1]
SERVER_DIR = API_DIR.parent / "server"
ADMIN = os.environ.get("TEST_PG_ADMIN", "postgresql://postgres:postgres@localhost:5432")
HOST = ADMIN.split("@", 1)[1]

USERS = {"staff": "p.sharma@bank.example", "lead": "r.menon@bank.example", "admin": "a.kapoor@bank.example"}
VOLATILE_KEYS = {"csrfToken", "requestId", "sessionId"}
# Lists compared as sets (order carries no meaning for the web app, which only tests membership).
SET_KEYS = {"capabilities"}
# Differences the Python platform introduces on purpose: (route regex, JSON path regex, reason).
EXPLAINED: list[tuple[str, str, str]] = [
    (
        r"^(POST /v1/auth/login|/v1/me)$",
        r"^/capabilities/\+(deployment|evals|members|rbac)\.",
        "capabilities of the new deployments, evals and tenant-administration features (platform plan §2)",
    ),
    (r"^/v1/auth/demo$", r"^/sso$", "additive `sso` flag telling the sign-in page whether OIDC is on (P-03)"),
]
ISO_RE = re.compile(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:\d{2})$")
UNKNOWN_TICKET = "00000000-0000-4000-8000-000000000000"

# Every GET route of the TS API (apps/server/src/routes/*.ts and app.ts), as templates.
ROUTES = [
    "/healthz",
    "/v1/auth/demo",
    "/v1/me",
    "/v1/sessions",
    "/v1/inbox",
    "/v1/tickets",
    "/v1/tickets/:id",
    "/v1/calls/:id",
    "/v1/activity",
    "/v1/shift",
    "/v1/search",
    "/v1/people",
    "/v1/insights/performance",
    "/v1/insights/results",
    "/v1/learning",
    "/v1/boards",
    "/v1/agents",
    "/v1/actions",
    "/v1/policies",
    "/v1/knowledge",
    "/v1/taxonomy",
    "/v1/admin",
    "/v1/audit/verify",
]
NOT_REPLAYED = {
    "/v1/stream": "server-sent events (long-lived); covered by the SSE tests",
    "/v1/oauth/:provider/callback": "needs a live OAuth state from a provider",
    "/v1/openapi.json": "generated by each framework; the contract is checked by gen_dto.py",
    "/readyz": "infrastructure probe",
    "/metrics": "Prometheus text, framework-specific series",
}


# ── Servers ──────────────────────────────────────────────────────────────────────────────────────────


def _admin_exec(sql: str, db: str = "postgres") -> None:
    with psycopg.connect(f"{ADMIN}/{db}", autocommit=True) as conn:
        conn.execute(sql)


def prepare_databases(source: str, targets: list[str]) -> str:
    """Seed `source` with the clock at the current minute, then clone it into each target."""
    now = datetime.now(UTC).replace(second=0, microsecond=0).isoformat().replace("+00:00", "Z")
    for db in (source, *targets):
        _admin_exec(
            f"select pg_terminate_backend(pid) from pg_stat_activity where datname = '{db}' "
            "and pid <> pg_backend_pid()"
        )
        _admin_exec(f'drop database if exists "{db}"')
    _admin_exec(f'create database "{source}"')
    subprocess.run(
        [sys.executable, "-m", "command_inbox.seed.cli", "--database-url", f"{ADMIN}/{source}", "--now", now],
        cwd=API_DIR,
        check=True,
    )
    for db in targets:
        _admin_exec(f'create database "{db}" template "{source}"')
    return now


def start_ts(db: str, port: int, log: Path) -> subprocess.Popen[bytes]:
    env = {
        **os.environ,
        "NODE_ENV": "development",
        "PORT": str(port),
        "HOST": "127.0.0.1",
        "DATABASE_URL": f"postgres://ci_app:ci_app@{HOST}/{db}",
        "DATABASE_ADMIN_URL": f"{ADMIN}/{db}",
        "DEMO_MODE": "true",
        "EMBEDDED_WORKER": "false",
        "LLM_PROVIDER": "heuristic",
        "LOG_LEVEL": "info",
    }
    return subprocess.Popen(
        ["node", "--import", "tsx", "src/main.ts"],
        cwd=SERVER_DIR,
        env=env,
        stdout=log.open("wb"),
        stderr=subprocess.STDOUT,
    )


def start_py(db: str, port: int, log: Path) -> subprocess.Popen[bytes]:
    env = {
        **os.environ,
        "APP_ENV": "development",
        "DATABASE_URL": f"postgresql+asyncpg://ci_app:ci_app@{HOST}/{db}",
        "DATABASE_ADMIN_URL": f"postgresql+asyncpg://{ADMIN.split('://', 1)[1]}/{db}",
        "DEMO_MODE": "true",
        "EMBEDDED_WORKER": "false",
        "LLM_PROVIDER": "heuristic",
        "DECISION_ENGINE": "heuristic",
        "LOG_LEVEL": "WARNING",
        "LOG_JSON": "false",
    }
    cmd = [sys.executable, "-m", "uvicorn", "command_inbox.main:create_app", "--factory"]
    cmd += ["--host", "127.0.0.1", "--port", str(port)]
    return subprocess.Popen(cmd, cwd=API_DIR, env=env, stdout=log.open("wb"), stderr=subprocess.STDOUT)


def wait_healthy(url: str, proc: subprocess.Popen[bytes], timeout: float = 60) -> None:
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        if proc.poll() is not None:
            raise SystemExit(f"server for {url} exited with {proc.returncode}; see its log")
        try:
            if httpx.get(f"{url}/healthz", timeout=2).status_code == 200:
                return
        except httpx.HTTPError:
            pass
        time.sleep(0.5)
    raise SystemExit(f"{url} did not become healthy in {timeout}s")


# ── Diffing ──────────────────────────────────────────────────────────────────────────────────────────


def _ts(v: Any) -> datetime | None:
    if isinstance(v, str) and ISO_RE.match(v):
        try:
            return datetime.fromisoformat(v.replace("Z", "+00:00"))
        except ValueError:
            return None
    return None


def diff(a: Any, b: Any, path: str = "", *, volatile_ids: bool = False) -> list[dict[str, Any]]:
    """JSON paths where the (normalised) values differ."""
    key = path.rsplit("/", 1)[-1]
    if key in VOLATILE_KEYS or (volatile_ids and key == "id"):
        return []
    if isinstance(a, dict) and isinstance(b, dict):
        out = []
        for k in sorted(set(a) | set(b), key=str):
            if k not in a or k not in b:
                if k not in VOLATILE_KEYS:
                    out.append(
                        {"path": f"{path}/{k}", "ts": a.get(k, "<absent>"), "py": b.get(k, "<absent>")}
                    )
                continue
            out += diff(a[k], b[k], f"{path}/{k}", volatile_ids=volatile_ids)
        return out
    if (
        key in SET_KEYS
        and isinstance(a, list)
        and isinstance(b, list)
        and all(isinstance(x, str) for x in a + b)
    ):
        return [{"path": f"{path}/-{x}", "ts": x, "py": "<absent>"} for x in sorted(set(a) - set(b))] + [
            {"path": f"{path}/+{x}", "ts": "<absent>", "py": x} for x in sorted(set(b) - set(a))
        ]
    if isinstance(a, list) and isinstance(b, list):
        out = []
        if len(a) != len(b):
            out.append({"path": f"{path}/length", "ts": len(a), "py": len(b)})
        for i, (x, y) in enumerate(zip(a, b, strict=False)):
            out += diff(x, y, f"{path}/{i}", volatile_ids=volatile_ids)
        return out
    if a == b:
        return []
    if (
        isinstance(a, (int, float))
        and isinstance(b, (int, float))
        and not isinstance(a, bool)
        and float(a) == float(b)
    ):
        return []
    ta, tb = _ts(a), _ts(b)
    if ta and tb and abs((ta - tb).total_seconds()) < 2:
        return []
    return [{"path": path or "/", "ts": a, "py": b}]


@dataclass
class Result:
    route: str
    user: str
    url: str
    ts_status: int
    py_status: int
    outcome: str  # identical | differing | missing | ts_error | error
    diffs: list[dict[str, Any]] = field(default_factory=list)
    explained: list[dict[str, Any]] = field(default_factory=list)


def explain(route: str, diffs: list[dict[str, Any]]) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    """Split diffs into (unexplained, explained-with-reason)."""
    open_, known = [], []
    for d in diffs:
        reason = next(
            (why for r, pth, why in EXPLAINED if re.search(r, route) and re.search(pth, d["path"])), None
        )
        (known if reason else open_).append({**d, "reason": reason} if reason else d)
    return open_, known


def _body(r: httpx.Response) -> Any:
    try:
        return r.json()
    except ValueError:
        return r.text


def classify(
    ts_r: httpx.Response, py_r: httpx.Response, volatile_ids: bool
) -> tuple[str, list[dict[str, Any]]]:
    if ts_r.status_code >= 500:
        return "ts_error", []
    if py_r.status_code in (404, 405) and ts_r.status_code not in (404, 405):
        return "missing", []
    d = []
    if ts_r.status_code != py_r.status_code:
        d.append({"path": "<status>", "ts": ts_r.status_code, "py": py_r.status_code})
    d += diff(_body(ts_r), _body(py_r), volatile_ids=volatile_ids)
    return ("identical" if not d else "differing"), d


# ── Corpus ───────────────────────────────────────────────────────────────────────────────────────────


def ticket_refs(listing: Any) -> list[tuple[str, str]]:
    items = listing.get("items", []) if isinstance(listing, dict) else []
    return [(t["id"], str(t["number"])) for t in items if isinstance(t, dict) and "id" in t]


def corpus(ts_client: httpx.Client) -> list[tuple[str, str]]:
    """(route template, concrete url) pairs for one signed-in user, ids taken from the TS responses."""
    reqs: list[tuple[str, str]] = [("/v1/me", "/v1/me"), ("/v1/sessions", "/v1/sessions")]
    for f in ("all", "auto", "draft", "manual", "late"):
        reqs.append(("/v1/inbox", f"/v1/inbox?filter={f}"))
    for q in (
        "",
        "?lane=auto",
        "?lane=manual",
        "?status=human",
        "?status=resolved",
        "?owner=mine",
        "?owner=ai",
        "?owner=unassigned",
        "?due=risk",
        "?conf=low",
        "?pri=P1",
        "?board=trade",
        "?q=statement",
        "?bucket=Disputed%20transactions",
    ):
        reqs.append(("/v1/tickets", f"/v1/tickets{q}"))
    listing = ts_client.get("/v1/tickets").json()
    refs = ticket_refs(listing)
    for tid, _number in refs:
        reqs.append(("/v1/tickets/:id", f"/v1/tickets/{tid}"))
    for _, number in refs[:5]:
        reqs.append(("/v1/tickets/:id", f"/v1/tickets/{number}"))
    reqs.append(("/v1/tickets/:id", f"/v1/tickets/{UNKNOWN_TICKET}"))
    reqs.append(("/v1/calls/:id", f"/v1/calls/{UNKNOWN_TICKET}"))
    for q in ("dispute", "48199", "Meera", "statement april", ""):
        reqs.append(("/v1/search", f"/v1/search?q={q}"))
    for route in ROUTES:
        if (
            ":" not in route
            and route not in {r for r, _ in reqs}
            and route not in ("/healthz", "/v1/auth/demo")
        ):
            reqs.append((route, route))
    return reqs


def sign_in(base: str, email: str) -> tuple[httpx.Client, dict[str, Any]]:
    client = httpx.Client(base_url=base, timeout=30)
    r = client.post("/v1/auth/login", json={"email": email})
    if r.status_code != 200:
        raise SystemExit(f"sign-in as {email} on {base} failed: {r.status_code} {r.text[:300]}")
    return client, r.json()


def run(ts_url: str, py_url: str) -> dict[str, Any]:
    results: list[Result] = []
    with ExitStack() as stack:
        anon_ts = stack.enter_context(httpx.Client(base_url=ts_url, timeout=30))
        anon_py = stack.enter_context(httpx.Client(base_url=py_url, timeout=30))
        for route, url in (
            ("/healthz", "/healthz"),
            ("/v1/auth/demo", "/v1/auth/demo"),
            ("/v1/me", "/v1/me"),
        ):
            results.append(replay(anon_ts, anon_py, route, "anon", url))

        for user, email in USERS.items():
            ts_client, ts_me = sign_in(ts_url, email)
            py_client, py_me = sign_in(py_url, email)
            stack.callback(ts_client.close)
            stack.callback(py_client.close)
            route = "POST /v1/auth/login"
            open_, known = explain(route, diff(ts_me, py_me))
            outcome = "identical" if not open_ else "differing"
            results.append(Result(route, user, "/v1/auth/login", 200, 200, outcome, open_[:25], known))
            for route, url in corpus(ts_client):
                results.append(replay(ts_client, py_client, route, user, url))
    return summarise(results)


def replay(ts_client: httpx.Client, py_client: httpx.Client, route: str, user: str, url: str) -> Result:
    try:
        a, b = ts_client.get(url), py_client.get(url)
    except httpx.HTTPError as err:
        return Result(route, user, url, 0, 0, "error", [{"path": "<transport>", "ts": str(err), "py": ""}])
    outcome, d = classify(a, b, volatile_ids=route == "/v1/sessions")
    open_, known = explain(route, d)
    if outcome == "differing" and not open_:
        outcome = "identical"
    return Result(route, user, url, a.status_code, b.status_code, outcome, open_[:25], known)


def summarise(results: list[Result]) -> dict[str, Any]:
    by_route: dict[str, list[Result]] = defaultdict(list)
    for r in results:
        by_route[r.route].append(r)
    routes: dict[str, str] = {}
    for route, rs in by_route.items():
        outcomes = {r.outcome for r in rs}
        routes[route] = (
            "identical"
            if outcomes == {"identical"}
            else "missing"
            if outcomes == {"missing"}
            else "ts_error"
            if outcomes == {"ts_error"}
            else "missing"
            if outcomes <= {"missing", "identical"} and "missing" in outcomes
            else "differing"
        )
    n = len(routes)
    counts = {
        k: sum(1 for v in routes.values() if v == k)
        for k in ("identical", "differing", "missing", "ts_error", "error")
    }
    reasons: dict[str, int] = defaultdict(int)
    for r in results:
        for e in r.explained:
            reasons[e["reason"]] += 1
    req_counts = {k: sum(1 for r in results if r.outcome == k) for k in counts}
    return {
        "generatedAt": datetime.now(UTC).isoformat(),
        "summary": {
            "routes": n,
            **{f"routes{k.title().replace('_', '')}": v for k, v in counts.items()},
            **{
                f"pct{k.title().replace('_', '')}": round(100 * v / n, 1) if n else 0
                for k, v in counts.items()
            },
            "requests": len(results),
            **{f"requests{k.title().replace('_', '')}": v for k, v in req_counts.items()},
        },
        "routes": dict(sorted(routes.items())),
        "explainedDifferences": dict(reasons),
        "notReplayed": NOT_REPLAYED,
        "results": [r.__dict__ for r in results],
    }


def main() -> int:
    p = argparse.ArgumentParser(description=(__doc__ or "").splitlines()[0])
    p.add_argument("--ts-url", default="http://127.0.0.1:4214")
    p.add_argument("--py-url", default="http://127.0.0.1:4114")
    p.add_argument("--start", action="store_true", help="seed, clone and start both servers here")
    p.add_argument("--source-db", default="ci_parity_src")
    p.add_argument("--ts-db", default="ci_parity_ts")
    p.add_argument("--py-db", default="ci_parity_py")
    p.add_argument("--out", type=Path, default=Path("parity-report.json"))
    p.add_argument("--logs", type=Path, default=None, help="where server logs go (default: next to --out)")
    args = p.parse_args()

    procs: list[subprocess.Popen[bytes]] = []
    try:
        if args.start:
            logs = args.logs or args.out.resolve().parent
            logs.mkdir(parents=True, exist_ok=True)
            seeded_at = prepare_databases(args.source_db, [args.ts_db, args.py_db])
            print(f"seeded {args.source_db} at {seeded_at}; cloned to {args.ts_db}, {args.py_db}")
            ts_port = int(args.ts_url.rsplit(":", 1)[1])
            py_port = int(args.py_url.rsplit(":", 1)[1])
            procs.append(start_ts(args.ts_db, ts_port, logs / "parity-ts.log"))
            procs.append(start_py(args.py_db, py_port, logs / "parity-py.log"))
            wait_healthy(args.ts_url, procs[0])
            wait_healthy(args.py_url, procs[1])
        report = run(args.ts_url, args.py_url)
    finally:
        for proc in procs:
            proc.terminate()
        for proc in procs:
            try:
                proc.wait(timeout=10)
            except subprocess.TimeoutExpired:
                proc.kill()

    args.out.write_text(json.dumps(report, indent=2, ensure_ascii=False, default=str))
    s = report["summary"]
    print(
        f"routes: {s['routes']} · identical {s['routesIdentical']} ({s['pctIdentical']}%) · "
        f"differing {s['routesDiffering']} ({s['pctDiffering']}%) · missing {s['routesMissing']} "
        f"({s['pctMissing']}%) · ts errors {s['routesTsError']}"
    )
    print(
        f"requests: {s['requests']} · identical {s['requestsIdentical']} · differing {s['requestsDiffering']} "
        f"· missing {s['requestsMissing']}"
    )
    for route, outcome in report["routes"].items():
        print(f"  {outcome:<10} {route}")
    for reason, n in report["explainedDifferences"].items():
        print(f"  explained ×{n}: {reason}")
    print(f"report: {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
